### ISSUE TITLE
positive color clues should light up pip in gold or something

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#1039]

**Comment by DrAnax** [comment]
This should no longer be an issue

**Comment by Zamiell** [comment]
why wouldn't it

**Comment by DrAnax** [comment]
Why would you need gold pips here?

![image](https://user-images.githubusercontent.com/2622043/153019697-c68a009b-527b-4183-b0dd-2b8b8bc464cf.png)

**Comment by Zamiell** [comment]
your screenshot isn't my concern

1) watch what happens to a pink card when it goes from having no clues on it to having one rank 2 clue on it
2) watch what happens to a rainbow-ones card when it goes from having no clues on it to having one blue clue on it

these two situations should have symmetry, and they currently do not

**Comment by Romain672** [comment]
Here is another option, make colors bigger:
![big](https://user-images.githubusercontent.com/12693191/153283263-2ccc8788-ce6c-49f2-9a4c-837756a15341.jpg)

**Comment by Zamiell** [comment]
making them bigger is kind of ugly, so i suspect that making them have a gold border would be better
(although I have not seen a screenshot yet with them having a gold border either)

**Comment by Romain672** [comment]
Or a line which start from the center into the color clued.
Maybe an arrow.

**Comment by DrAnax** [comment]
Better?

![image](https://user-images.githubusercontent.com/2622043/153507199-61532657-eaa4-428d-ac03-27144517fb1d.png)

**Comment by DarthGandalf** [comment]
It looks very heavy

**Comment by DarthGandalf** [comment]
at very least, no shadow behind the circle

the circle itself is huge

making the color more subtle might help, dunno

try the gold border instead of circle?

**Comment by DarthGandalf** [comment]
Can you share the code what you did so far to plumb the parameters? I can also try to poke the graphics a bit

**Comment by DrAnax** [comment]
omw

**Comment by DrAnax** [comment]
drawPips.ts 3370

**Comment by DrAnax** [comment]
I think the Rainbow pip should never be highlighted because there's no "Rainbow" Color clue. Highlight (after this PR) means "positive information" and PO "Rainbow" can never be given.

**Comment by DrAnax** [comment]
Their respective pips should; clues can get them.

**Comment by DrAnax** [comment]
There's no "mahogany" pip, only red and purple

**Comment by nitawa-hl** [comment]
Ok, then I think I have it, give me a sec and I push again to my fork so you can test it if you want :)

**Comment by nitawa-hl** [comment]
I fixed the problem with the yellow pip, now the only issue is that it overlaps with the 1

![image](https://user-images.githubusercontent.com/83447589/153649290-44035009-0068-4446-8b4d-a276780efe25.png)

**Comment by nitawa-hl** [comment]
With slightly smaller rank pip

![image](https://user-images.githubusercontent.com/83447589/153673546-337aa524-cab5-4c7a-9406-cb11671c4476.png)

low(er) res
![image](https://user-images.githubusercontent.com/83447589/153673592-39625e03-0eec-4880-b52e-1cfb50f04cd9.png)

**Comment by nitawa-hl** [comment]
Alternative:

- Pips closer together
- Rank smaller (but less so)

5suits
![image](https://user-images.githubusercontent.com/83447589/153680102-1014bc11-66f8-425a-b584-75adfd9c6815.png)

6suits
![image](https://user-images.githubusercontent.com/83447589/153680192-d45f01a9-5301-4709-8fb9-af874649844f.png)

**Comment by DrAnax** [comment]
Nice work

**Comment by Romain672** [comment]
Yeah I like it too. Not highlighting the middle look best to me.

Should this be on all the time?
I wanted to list all variants, but that look limited to:
1) -Ones & -Fives with muddy rainbow / rainbow / or omni
2) Synesthesia

**Comment by DarthGandalf** [comment]
@Romain672 How do you imagine this for "no variant"? If the card got red clue and 4 clue, why keep showing all the pips which the card can't possibly be anymore?

**Comment by DarthGandalf** [comment]
@nitawa-hl not a big fan of making the number smaller than it is now, but looks fine, yes. This is what I imagined by a gold border, but I [failed](https://github.com/Hanabi-Live/hanabi-live/pull/2593#issuecomment-1035702064) to implemented that myself

**Comment by Romain672** [comment]
> @Romain672 How do you imagine this for "no variant"? If the card got red clue and 4 clue, why keep showing all the pips which the card can't possibly be anymore?

Leave it as it is now: the card will be known red.
And in rainbow variant, the card will be known red or rainbow.

**Comment by nitawa-hl** [comment]
@Zamiell Since there doesn't to seem to be a overwhelmingly preferred option, choose one or the other, it doesn't really matter which. We can even try one and if people complaint go back and try the other one, or even allow for both options as a settings thing. But can you just merge one of the PRs? It feels dumb to leave this issue hanging because there's more than one option when the work is done.
