### ISSUE TITLE
Click + Drag off pop-up Menus closes Menu

### ISSUE THREAD

**Issue by EhDrone** [Hanabi-Live/hanabi-live#1095]
Clicking mouse button on a pop-up menu, and letting go off of the pop-up menu causes the menu to close:
- Create Game
- Watch Specific Replay
- Resources
- Settings.

**Comment by Zamiell** [comment]
yeah this is pretty hard to fix, do you want to submit a PR?

**Comment by DrAnax** [comment]
No longer valid, these were all replaced by dialogs.

**Comment by Zamiell** [comment]
ok
