### ISSUE TITLE
rename users with space to underscore

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#1103]

**Comment by Zamiell** [comment]
or delete them

**Comment by DrAnax** [comment]
View changes:
`SELECT id, username, REPLACE(username, ' ', '_'), datetime_last_login FROM "users" WHERE username LIKE '% %' ORDER BY datetime_last_login DESC;`

Update, under underscore
`UPDATE users SET username = REPLACE(username, ' ', '_');`

Verify
`SELECT COUNT(*) FROM "users" WHERE username LIKE '% %';`

I can also submit a PR which will replace space with underscore during login if you want.

**Comment by Zamiell** [comment]
seems to have worked, thank you very much!
