### ISSUE TITLE
Spectate a pre-game

### ISSUE THREAD

**Issue by padiwik** [Hanabi-Live/hanabi-live#1253]
Often I want to chat in a pregame lobby without fear that the game would start suddenly. Currently the solution is to /msg people who are in it, which is not ideal

**Comment by padiwik** [comment]
(Or join voice, but that doesnt always work with newbies)

**Comment by Zamiell** [comment]
propose a ui

**Comment by DrAnax** [comment]
> seems fine. i guess the text should also say "Alice joined (as a spectator)." or something like that

Should players trying to enter a full game enter as spectators instead of getting a "table full" message?

Should players be able to enter as spectators in a p/w protected game?

**Comment by Zamiell** [comment]
> Should players trying to enter a full game enter as spectators instead of getting a "table full" message?

sure

> Should players be able to enter as spectators in a p/w protected game?

no, they must wait for the game to start
