### ISSUE TITLE
assign legacy prefix to games that have the wrong starting player

### ISSUE THREAD

**Issue by scharkbite** [Hanabi-Live/hanabi-live#1397]
I always suspected this has happened before, and now hopefully, I have proof.  The following four games all used the same seed:

1. 231965
2. 191880
3.  73934
4.  62187

The deals look identical, but in games 3 and 4, a different player went first!

**Comment by Zamiell** [comment]
that's unfortunately expected, because legacy games can have different starting players, and i didn't care to reshuffle them to have a separate seed. its something i'll do at some point though, maybe

**Comment by Zamiell** [comment]
the fix is to use some prefix for the seed, e.g. "legacy-"
then when it actually uses the seed, it trims off the legacy prefix before seeding the rng

**Comment by DrAnax** [comment]
How can we tell if the game with MAX(id) per seed has the correct starting player?

**Comment by Zamiell** [comment]
use starting_player != 0 I think
see: https://github.com/Hanabi-Live/hanabi-live/blob/main/install/database_schema.sql#L127-L131

**Comment by DrAnax** [comment]
This should solve the problem:

`UPDATE games SET seed = CONCAT('legacy-', starting_player, '-', seed) WHERE starting_player <> 0;`

Puts `legacy-<int>-` in front of problematic seeds, separating them from others and combining them if they have the same starting player.

**Comment by Zamiell** [comment]
ok, but it needs a code change as well right? because then the decks won't line up anymore when you view the replay

**Comment by DrAnax** [comment]
Right, I'll PR that part

**Comment by Zamiell** [comment]
ok

**Comment by Zamiell** [comment]
ok should i run the db command now

**Comment by DrAnax** [comment]
Is this done?

**Comment by Zamiell** [comment]
should i run the db command now

**Comment by DrAnax** [comment]
The PR was accepted, right? If so you may run the query

**Comment by Zamiell** [comment]
ok i did
