### ISSUE TITLE
Hypothetical Mode Incorrect Pips

### ISSUE THREAD

**Issue by Elatekur** [Hanabi-Live/hanabi-live#1614]
In hypothetical mode, when a 2, 3 or 4 is discarded, I have noticed that if someone else has the other copy of that card with the colour filled in, the correct state of the card will be ruled out by the pips as though there were only one copy of the card. For example, if r3 has been discarded and someone has the other r3 clued red, the 3 will often be crossed out when you click on the card. I'm not sure if this always happens or whether it happens with 1s.

**Comment by DrAnax** [comment]
cannot reproduce, not valid anymore
