### ISSUE TITLE
Resizing the window causes arrows to go to the wrong place

### ISSUE THREAD

**Issue by robertos** [Hanabi-Live/hanabi-live#1646]
They are probably calculated in absolute not relative terms

**Comment by Zamiell** [comment]
current player area is also bugged

**Comment by DrAnax** [comment]
resizing the window doesn't change anything, /close?

**Comment by Zamiell** [comment]
this was when rob added the resizing code, which i reverted

this was a TODO issue for putting the code back, but since rob is mia, i guess we can close this now
