### ISSUE TITLE
Game ends while in replay, use shared turns, play stacks disappear and deck becomes b3. No errors in console

### ISSUE THREAD

**Issue by timotree3** [Hanabi-Live/hanabi-live#1680]
![Screenshot from 2020-08-24 12-15-38](https://user-images.githubusercontent.com/6473438/91069685-b558af80-e603-11ea-9694-4f4ab0832e4a.png)

**Comment by Zamiell** [comment]
for any of the players or just the spectator?

**Comment by timotree3** [comment]
just spectator it seems like

**Comment by timotree3** [comment]
I still have the tab open if you want me to run any commands.

**Comment by timotree3** [comment]
![Screenshot from 2020-08-24 12-22-48](https://user-images.githubusercontent.com/6473438/91070291-8bec5380-e604-11ea-9d3a-67fb8f60dd56.png)
As the review progresses, cards are going onto the disappeared play stacks so now they look normal. Also the deck returned to not being b3

**Comment by Zamiell** [comment]
tim says he can't repro so not sure what to do about this

**Comment by Zamiell** [comment]
i think this might have been an unrelated bug that has since been fixed.
reopen if it happens again

**Comment by timotree3** [comment]
![Screenshot from 2020-08-28 17-37-29](https://user-images.githubusercontent.com/6473438/91617102-3d68ed00-e955-11ea-9713-b2d950e421eb.png)
happened again in up and down. different circumstances

**Comment by Zamiell** [comment]
no errors?

**Comment by timotree3** [comment]
no errors

**Comment by timotree3** [comment]
I moved forward and back a bit and the play stack placeholders reappear after a card is played and then rewound. also after like 7 turns the i3 changed to a y3. want me to run any commands with the tab open?

**Comment by Zamiell** [comment]
not really. i assume you were a spectator when the game ended?
use json import and try to reproduce the problem

**Comment by timotree3** [comment]
this time I was spectating for a while and then when the leader rewound to the beginning of the game the cards were glitched (I don't remember how exactly) and then when I moved forward a turn they all flew into different places and the deck became i3

I can use JSON import to try to reproduce

**Comment by timotree3** [comment]
just trying by using the same shared replay. I'm doing similar things with no luck. a common theme in the two natural occurences though seems to be being teleported to the first turn of a shared replay of Up or Down.

**Comment by timotree3** [comment]
and in both cases I was taken to the first turn of the game by means outside of my control. either the leader or the game ending while I was in a side replay

**Comment by timotree3** [comment]
It happened again. This time not an up or down game. I was spectating, then the game ended, when the replay was taken back to the beginning at first all of the hands disappeared and the clue arrows were pointing at the 5's play stacks, and then all the cards snapped into place, the play stack placeholders were wrong, and the deck looked like a normal card

**Comment by DrAnax** [comment]
Status of this?

**Comment by Krycke** [comment]
Timo, has still happened in the near present, or is this solved?

**Comment by Zamiell** [comment]
i'll close for now
