### ISSUE TITLE
Pause Bug

### ISSUE THREAD

**Issue by Dr-Kakashi** [Hanabi-Live/hanabi-live#1687]
![2020-08-25_20-32-58](https://user-images.githubusercontent.com/48993588/91252974-8d587180-e713-11ea-946d-3fca84576af6.png)

Schark had 20 seconds left on the clock so I did the /pause command.
Schark unpaused, which then the timer's look weird and said he had 2:30 seconds on the clock
I believe he used more than 20 seconds, though I'm not 100% sure.  
Then when schark clued me, the game immediately ended saying I ran out of time.

**Comment by DrAnax** [comment]
now that the timer has been fixed, this may no longer be an issue, /close?

**Comment by Zamiell** [comment]
sure
