### ISSUE TITLE
Leaderboard for every Variant

### ISSUE THREAD

**Issue by Dr-Kakashi** [Hanabi-Live/hanabi-live#1759]
It would be nice to have a leaderboard for every variant to see the team that currently has a max score for that variant.   

![image](https://user-images.githubusercontent.com/48993588/93703476-77e52600-facc-11ea-8ca4-0d46a24edf46.png)

For example, here you can see that there are a total of 10 perfect scores, but none of them are listed on the front page as it only shows the most current games.  

It would be nice to see those max scores to have a quick reference.  Where you can sort by player count, date and other stats. 

https://github.com/Zamiell/hanabi-live/issues/1092

**Comment by vEnhance** [comment]
Right now you can currently filter by a given score (probably the max score) and number of players.

In order to sort rather than filter, would need to implement the API change mentioned in https://github.com/Hanabi-Live/hanabi-live/issues/2755#issuecomment-1358362636
