### ISSUE TITLE
Bugs with Throw It In A Hole

### ISSUE THREAD

**Issue by Dr-Kakashi** [Hanabi-Live/hanabi-live#1761]
I'm noticing some intense lag while playing throw it in a hole both in replay and during gameplay.
Writing notes is.....a problem.  Sometimes you can write notes between cards and other times you have to go into the replay in order to write notes.

**Comment by Aigul9** [comment]
as for me, it is impossible to leave a note by clicking in the middle of the card. it works only in the top left corner (i didn't check others)

**Comment by atrich** [comment]
I've seen that with no variant TIIAH, you must refresh the page to take a note on green. Additionally, once the game is over you can't change the notes, which makes it difficult to see the 'actual' replay.

**Comment by Romain672** [comment]
That bug happen twice: today and yesterday.
You play your game normally.
And then you discard a card.
After discarding, the game froze and you got what is below.
So I hardly refreshed (ctrl+f5), and then in the following turns, it wasn't really fun. It takes 30s to load, I need to refresh every turn.

![bug](https://user-images.githubusercontent.com/12693191/151684403-b4e85616-8128-477a-a2a1-83f5629d49fb.jpg)

**Comment by Zamiell** [comment]
copy paste the javascript errors

**Comment by Romain672** [comment]
Connection.ts:78 Object
Connection.ts:77 Sent replayAction:
Connection.ts:78 Object
Connection.ts:77 Sent replayAction:
Connection.ts:78 Object
Connection.ts:49 Received chatTyping:
Connection.ts:50 Object
Connection.ts:49 Received hypoAction:
Connection.ts:50 {"type":"play","playerIndex":0,"order":51,"suitIndex":3,"rank":4,"failed":false}
cardLayoutView.ts:162 Uncaught TypeError: Cannot read properties of undefined (reading 'children')
    at a (cardLayoutView.ts:162:24)
    at cardLayoutView.ts:167:19
    at Array.forEach (<anonymous>)
    at Mh (cardLayoutView.ts:160:15)
    at Object.onChange (cardLayoutView.ts:137:3)
    at observeStore.ts:47:11
    at Array.forEach (<anonymous>)
    at i (observeStore.ts:43:8)
    at Object.p [as dispatch] (redux.js:296:32)
    at gameCommands.ts:130:3


Is it the right one? There is 'hypoAction' which look like for hypthetical, and yeah it was bugged too.

**Comment by vEnhance** [comment]
Closing as dupes of https://github.com/Hanabi-Live/hanabi-live/issues/1610 and https://github.com/Hanabi-Live/hanabi-live/issues/1630, please re-open if I misunderstood
