### ISSUE TITLE
add "Num. of Finesses Needed" to future eff tooltip

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#1864]
"Num. of Finesses Needed" = the amount of 2-for-1 clues that you need to give before future efficiency reaches <= 1.00

**Comment by Zamiell** [comment]
@vEnhance do you want to try implementing this?

**Comment by vEnhance** [comment]
Sure. Is this just number of cards to get minus number of possible clues?

**Comment by Zamiell** [comment]
"Num. of Finesses Needed" = the amount of 2-for-1 clues that you need to give before future efficiency reaches <= 1.00

so you have to project future eff by decrement cards gotten by 2 and decrement clues by 1
and then do that N times until future eff <= 1.00

**Comment by timotree3** [comment]
Pretty sure both of your algorithms give the same answer

**Comment by Zamiell** [comment]
i only described 1 algorithm

**Comment by timotree3** [comment]
the two of you described one each

**Comment by Zamiell** [comment]
oh, i see

**Comment by DrAnax** [comment]
This is already implemented in the tooltip

**Comment by Zamiell** [comment]
ok ill close then

**Comment by DrAnax** [comment]
You haven't
