### ISSUE TITLE
sound effect for pause/unpause

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#1922]

**Comment by Zamiell** [comment]
anyone have any ideas for sound effects

**Comment by DrAnax** [comment]
For unpause: https://www.zapsplat.com/music/alarm-clock-ticking/

For pause: https://www.zapsplat.com/music/antique-clock-ticker-tick-tock-could-be-watch-or-used-for-a-countdown/

These are both lengthy mp3, they can certainly be reduced to 8-10 ticks for the first one and 4 ticks for the second.

**Comment by Zamiell** [comment]
a single tick of the second one is fine for pausing, and a single tock of the second one is fine for unpausing

**Comment by DrAnax** [comment]
Check these two

[sounds.zip](https://github.com/Zamiell/hanabi-live/files/7463116/sounds.zip)

**Comment by Zamiell** [comment]
seems fine, so slow tick for pause, and fast tick for unpause?

**Comment by DrAnax** [comment]
yes

**Comment by Zamiell** [comment]
might want to also double check that the volume is normalized with the other sounds

**Comment by DrAnax** [comment]
will do
