### ISSUE TITLE
All or Nothing option UI shenanigans.

### ISSUE THREAD

**Issue by hanabirnoob** [Hanabi-Live/hanabi-live#1953]
First, during pre-game, the mouse-over tooltip for the icon is missing, unlike for "extra card" or "one less card" option.

Second, during the game. the pace is shown even though pace is not an issue with that option enabled.

**Comment by Zamiell** [comment]
I mean we might as well show the pace, rather than showing "-" or something

**Comment by timotree3** [comment]
I tried playing All or Nothing and it's so terrible. None of the things that normally make your decisions matter in Hanabi apply. I would rather delete the mode than write code for it.

**Comment by hanabirnoob** [comment]
In double dark mode, things matter more.
