### ISSUE TITLE
Variant proposal: Funnel and Chimney

### ISSUE THREAD

**Issue by jack67889** [Hanabi-Live/hanabi-live#2027]
### Funnel

A number clue touches all cards with an equal or lower rank. So:

- 5 clue touches: 5,4,3,2,1
- 4 clue touches: 4,3,2,1
- 3 clue touches: 3,2,1
- 2 clue touches: 2,1
- 1 clue touches: 1

### Chimney

Basically the opposite of Funnel. A number clue touches all cards with an equal or higher rank. So:

- 1 clue touches: 1,2,3,4,5
- 2 clue touches: 2,3,4,5
- 3 clue touches: 3,4,5
- 4 clue touches: 4,5
- 5 clue touches: 5

**Comment by IceSelkie** [comment]
I believe this was added in PR #2675 and PR #2690 .

**Comment by Zamiell** [comment]
yep
