### ISSUE TITLE
When determining "brand new cards introduced", already given colour clues are ignored, at the time of giving clue.

### ISSUE THREAD

**Issue by Hari3** [Hanabi-Live/hanabi-live#2089]
In this following board position, griff has b4, clued with blue and b5 is fully know.
![image](https://user-images.githubusercontent.com/10483303/107141782-1e817480-6951-11eb-8b78-5fd636357c30.png)

When Hari tries to clue blue to griff, this is what they see:
![image](https://user-images.githubusercontent.com/10483303/107141796-280adc80-6951-11eb-9a3e-907cb9c051cd.png)

The black arrow on b5 is correct, but the white arrow on b4 is incorrect. It is not an untouched card.
After the clue is given, this is what everyone sees
![image](https://user-images.githubusercontent.com/10483303/107141806-33f69e80-6951-11eb-81ff-f1c8b8d4a89b.png)

I think that the colour clues in hand is ignored when determining "brand new cards introduced". This seems to happen only during clue giving phase. In the following scenario, Hari was clued only reds previously. When red is clued again, both cards are ignored when determining brand new card introduced:
![image](https://user-images.githubusercontent.com/10483303/107141830-66a09700-6951-11eb-8570-8abdb9fe9197.png)

**Comment by padiwik** [comment]
It's because both arrows invoke this code:

https://github.com/Zamiell/hanabi-live/blob/478cd91d88a4f5d8c4433b83a08e5e73e8533671/client/src/game/ui/arrows.ts#L103

where the if statement was written from the perspective of the clue already being given and public. I assume the fix is to add ` || element.state.num

**Comment by Hari3** [comment]
Aah, I has nothing to do with the fact that the clue was a colur clue. If there is only _one_ clue on a card, it will get a white arrow during cluing phase.
