### ISSUE TITLE
Morphed Play Piles In Replay

### ISSUE THREAD

**Issue by Smandon1** [Hanabi-Live/hanabi-live#2097]
When playing 'Throw It in a Hole', I often put notes on the play piles to keep track of what I think happened.  When the game ends, those piles continue to show the last morphed identity.  If I go back into my history and view a game then the piles look fine.

To reproduce:
1) Start a 'Throw It in a Hole' game.
2) Put a '1' note on the red play pile.
3) End the game

In the immediate replay created, the play pile will still show a red 1 when it should be empty.

**Comment by DrAnax** [comment]
According to #2110 this has been fixed and it should be closed

**Comment by Zamiell** [comment]
ok
