### ISSUE TITLE
Add new variant: sudoku

### ISSUE THREAD

**Issue by newduke** [Hanabi-Live/hanabi-live#2115]
Sudoku variant.

Each stack must start at a different rank (other plays are bombs)
Each subsequent play must be the next (cyclic) rank (eg, 2..3..4..5..1)
Stack is complete when it has all ranks.

Each suit has 2 of each rank because the variant is symmetric by rank.

**Comment by cjwomack** [comment]
Sounds interesting... but what would be sudoku variant conventions? So no saving of 2 or 5s... And would the starting convention to try to clue two cards eg... r2 and r3 are next to each other in someones hand so clue red?

**Comment by timotree3** [comment]
On turn 1 you could simply blind play a slot of your choosing :laughing:

**Comment by jakestiles** [comment]
This seems fun!

If this is too easy, perhaps it could be changed so each color has a rank that it is forced to start at. Leftmost color starts at 1, next color starts at 2, etc.

**Comment by newduke** [comment]
It's quite easy to force each suit to start at its rank, but "sudoku" (the original) doesn't have that restraint and I think it will be interesting to see how players use that to their advantage. 

I suspect that this variant will be a bit easy, but we can add several dark suits or other peculiarities to spice it up.

**Comment by Romain672** [comment]
To make it easier to play I got this idea:
 - r0, y1, g2, b3, p4 are initially played on stacks
 - yellow suit goes from 2 to 6
 - green suit goes from 3 to 7
 - blue suit goes from 4 to 8
 - purple suit goes from 5 to 9
 - 1 clue touch 1&6
 - 2 clue touch 2&7
 - 3 clue touch 3&8
 - 4 clue touch 4&9

This is similar than the first post, buy is maybe more easy to play.

**Comment by kesslermaximilian** [comment]
We should close this now.
