### ISSUE TITLE
Spectating "Throw it in a hole" from one player's perspective doesn't work

### ISSUE THREAD

**Issue by mdavidson29** [Hanabi-Live/hanabi-live#2118]
Trying to spectate "Throw it in a hole" from the perspective of a particular player is broken and there are errors in the console.  

Is this sufficient for debugging, or do you need additional information?

<img width="366" alt="Screen Shot 2021-03-04 at 8 44 29 PM" src="https://user-images.githubusercontent.com/30240608/110074450-14774980-7d36-11eb-9128-88d7d91b5fa3.png">
<img width="904" alt="Screen Shot 2021-03-04 at 8 44 35 PM" src="https://user-images.githubusercontent.com/30240608/110074457-16d9a380-7d36-11eb-847e-a7d4d999b7a8.png">
<img width="363" alt="Screen Shot 2021-03-04 at 8 45 02 PM" src="https://user-images.githubusercontent.com/30240608/110074466-1a6d2a80-7d36-11eb-910c-53ac7b540cfe.png">
<img width="365" alt="Screen Shot 2021-03-04 at 8 45 17 PM" src="https://user-images.githubusercontent.com/30240608/110074469-1a6d2a80-7d36-11eb-8cd3-fb75e8d76f71.png">

**Comment by argothiel** [comment]
I'm getting a different behavior, trying to spectate from other player's perspective:

![throw it in a hole](https://user-images.githubusercontent.com/13932353/183267954-062c3c55-242a-4a66-a14a-f538550f16d6.png)
:

**Comment by vEnhance** [comment]
Also #2610
