### ISSUE TITLE
playing a card in hypo of throw it in a hole breaks hypo until ended

### ISSUE THREAD

**Issue by timotree3** [Hanabi-Live/hanabi-live#2180]
Steps:

1. Go to https://hanab.live/shared-replay/520426#1
2. Blind play slot 4
3. Try making a move as Bob (you can't)
4. End the hypo. The blue 1 you blind-played is missing
5. Go forward and backward a few turns. The blue 1 has reappeared

**Comment by Krycke** [comment]
This one is solved
