### ISSUE TITLE
The empty clues warning during speedruns.

### ISSUE THREAD

**Issue by jatloe** [Hanabi-Live/hanabi-live#2198]
Hello. An issue I have found is that sometimes, when you pre-clue a card that gets discarded, the clue will touch nothing and there will be a warning that pops up, saying that you cannot give a clue that touches no cards. Except, that basically kills the run because of having to close the warning. Could this be changed to more of a sound effect?

**Comment by Zamiell** [comment]
submit a pr

**Comment by DrAnax** [comment]
Maybe all warnings during speedruns should be presented as timed self-closing toast messages instead of warning dialogs

**Comment by Zamiell** [comment]
i think better is to fix the cause, not the symptom

**Comment by DrAnax** [comment]
> i think better is to fix the cause, not the symptom

You mean, in speedruns, if a pre-clue is no longer valid to just ignore it?

**Comment by Zamiell** [comment]
yes
