### ISSUE TITLE
flashing notes on stacks

### ISSUE THREAD

**Issue by Aigul9** [Hanabi-Live/hanabi-live#2229]
https://user-images.githubusercontent.com/46625461/127057287-bdeed4a3-d5b1-4e53-8031-05f1ab025630.mp4
it feels like not all suits are affected

**Comment by Zamiell** [comment]
does this still happen?

**Comment by Aigul9** [comment]
yes

**Comment by Aigul9** [comment]
on light pink here: https://hanab.live/shared-replay/675563#58

**Comment by Zamiell** [comment]
doesn't happen for me

**Comment by Aigul9** [comment]
i am using 75% scaling

**Comment by Zamiell** [comment]
doesn't happen for me using 75% scaling

**Comment by Aigul9** [comment]
i think it happends when tooltips are multidirectiona
![2021-12-12_19-48-56](https://user-images.githubusercontent.com/46625461/145721464-4c0e2209-3902-46d2-a7ac-54488d91f762.png)
![2021-12-12_19-49-08](https://user-images.githubusercontent.com/46625461/145721467-25cce0d8-2ff0-4fe4-9cf9-8f73bc3ac820.png)

l

**Comment by Zamiell** [comment]
can you stop closing an reopening issues? it spams my notifications

**Comment by Aigul9** [comment]
turn them off

**Comment by Zamiell** [comment]
turn what off, my github notifications?

**Comment by Aigul9** [comment]
your github notifications

**Comment by Aigul9** [comment]
can you stop complaining that you received 4 extra notifications?

**Comment by vEnhance** [comment]
Closing since can't reproduce either
