### ISSUE TITLE
Frozen game during Throw It In A Hole

### ISSUE THREAD

**Issue by Dr-Kakashi** [Hanabi-Live/hanabi-live#2240]
![image](https://user-images.githubusercontent.com/48993588/127722840-f0849982-8f63-4faf-8448-1c0d4e24e9e5.png)

https://hanab.live/replay/599110

Game ID: 599110
Seed: p2v1233s1

Kimbi and I were playing Throw It in a Hole and noticed that there are times where the page becomes unresponsive so we have to refresh, which ends up showing the image above. 

The first game it happened in, we resolved the issue by having one of us refresh, while the other player refreshes first. The first player that refreshes is able to do their move, then has to refresh, to let the next player do their move.  We did this back and forth until it allows both of us into the game to continue. 

It happens generally towards the end of the game, right now in the game we're currently in, it is turn 60. 

Other players are able to spectate the table.

The console shows nothing as if the page didn't even attempt to load. Even though you can see that the table is partially loaded.  I know it's currently showing the Element tab. All the other tabs are also blank.

It timed out the first time so we started the game again with the replay turn command. Currently, Kimbi and I are being held prisoners until the game automatically times out.  Please save us from Hanabi Jail!

**Comment by DrAnax** [comment]
Looks like a possible deadlock or internet service failure of some kind (bad connection, attack on DO etc). Given that it can't be reproduced consistently, I'd say it's not a bug, in the general sense. /close ?

**Comment by Zamiell** [comment]
ok
