### ISSUE TITLE
Add score histograms to seed history

### ISSUE THREAD

**Issue by praccu** [Hanabi-Live/hanabi-live#2257]
Hi!

I'd like to add a histogram of scores to the seed history page.

I figure I can calculate them here: https://github.com/Zamiell/hanabi-live/blob/master/server/src/command_history_get_seed.go

Any objections or suggestions before I get cracking?

**Comment by Zamiell** [comment]
the seed history page at which url endpoint?

**Comment by Zamiell** [comment]
any updates on this?

**Comment by praccu** [comment]
I'm trying to find an elegant way to render the histogram that doesn't require importing libraries or complex CSS. Playing with that got distracting.

**Comment by timotree3** [comment]
If you're not gonna use CSS or have a library use CSS for you, the only alternatives I'm aware of are HTML Canvas and SVG. Is dynamically generating an SVG a good candidate?

**Comment by praccu** [comment]
"complex CSS". I think I can get it done with a few simple rules.

**Comment by praccu** [comment]
I finally got time to look at this, and when I ran "run.sh", Windows defender picked up a trojan (presumably in one of the libraries?). 

FYI / fair warning.

![hanabi-trojan](https://user-images.githubusercontent.com/92187022/143937400-28778ce9-4ff2-4465-ba82-47bb89f02251.png)

**Comment by Zamiell** [comment]
yeah thats almost certainly a false positive because it is opening up ports on your computer, which is expected

**Comment by praccu** [comment]
Moving on...

Is there some fake data that can be easily loaded into the database, for testing? 

There are three test cases:
-> No one has played this game ID before
-> One person has played this game ID before
-> multiple people have played this game ID before

Plus various sub-cases I want to exercise.

If not maybe putting together some fake data would be useful for ongoing development for other folks?

**Comment by Zamiell** [comment]
there's no fake data currently, if you want to make some that might be a nice thing to PR
