### ISSUE TITLE
[Variant] Odds & Evens

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2299]
"Those 3 cards are odds."

**Comment by Zamiell** [comment]
i dont get it

**Comment by Romain672** [comment]
It's 'Number blind' but with two extra hints: odds or evens.

**Comment by Zamiell** [comment]
@DrAnax i played it today and its pretty fun, you can do a PR to expand it with the other suits if you want

maybe first we should do the Efficiency thing refactoring
