### ISSUE TITLE
[Variant] Dual color 4 Colors (6 Suits)

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2381]
Hi,
This idea came from LilianaSkyMage.

Suit A is touched by colors 1&2
Suit B is touched by colors 1&3
Suit C is touched by colors 1&4
Suit D is touched by colors 2&3
Suit E is touched by colors 2&4
Suit F is touched by colors 3&4

And so:
Color 1 touch suits ABC
Color 2 touch suits ADE
Color 3 touch suits BDF
Color 4 touch suits CEF

**Comment by vEnhance** [comment]
Dual-color mix already implements this, please correct me if I'm wrong

**Comment by Romain672** [comment]
Nope, dual color mix is ab, bc, cd, da, rainbow, white.

**Comment by vEnhance** [comment]
Ah you're right. OK. For the bucket list.

**Comment by vEnhance** [comment]
Two ideas I had:

In **RGB mix**, the colors are red, green, blue and the suits are red (R), green (G), blue (B), purple (RB), teal (BG), yellow (RG). This is the Romain's proposal except with 3 colors.

In **CMYK**, we have cyan, magenta, yellow, black. And the colors are:
Red (MY)
Green (CY)
Blue (CM)
Teal?? (CK)
Yellow?? (YK)
Purple?? (MK)

The second one makes not much sense to me. I'd love to have better suit and color names here.

**Comment by Romain672** [comment]
I just checked, apparently it already exist on the name...
'Dual-Color (6 Suits)'.

But it's really weird since it seem that dual color 5 Suits or 6 Suits with a special suit is just ab bc cd de ae x.
While the exact Dual color 6 Suits is ab ac ad bc bd cd.

I wasn't aware of that, I believe I never played with the color 'Tan' because the name is so confusing.

Dual color 6 Suits look like to be ab bc cd de ef af.

Guess I will close then and ask a rename in a new subject.
If anyone is interrested by creating that dual color 6 Sutis ab bc cd de ef af, feel free to create another request.
