### ISSUE TITLE
Clue cannot be selected

### ISSUE THREAD

**Issue by timotree3** [Hanabi-Live/hanabi-live#2398]
Occasionally, when in a game. I try to give a clue by clicking on a color, and nothing happens. The button corresponding to the color is not selected, the clue is not highlighted, and "Give Clue" is disabled. In order to work around this, I have to click several other colors until finally a preview appears, at which point I can go back and click on my desired color.  This has been happening for about a week.

Relatedly, sometimes I click a color/number, and the clue preview highlights all of the card of that type except slot 1.

It seems like the clue preview has some lag with being able to clue slot 1.

I just tried reproducing this in a game where I tabbed between two players, and it didn't work. Perhaps it's time-sensitive and will require two people to reproduce.

**Comment by DrAnax** [comment]
> I just tried reproducing this in a game where I tabbed between two players, and it didn't work. Perhaps it's time-sensitive and will require two people to reproduce.

When I was look about the bug, regarding the new options proposal from guest, I finally managed to reproduce the bug using two different browsers. It would work as intended when using two tabs of the same browser. Maybe try that?

**Comment by DrAnax** [comment]
stale ?

**Comment by timotree3** [comment]
It still happens. I haven't been working on it but just because nobody's working on a bug doesn't mean we should close it IMO

**Comment by DrAnax** [comment]
Of course not. Stale was meant as "did you discover anything or was it a one time only"

**Comment by Krycke** [comment]
Is this bug still occuring?

**Comment by Zamiell** [comment]
i've never had this happen, so i'll close for now

seems like it might be related to the stale arrows bug that happens when you clue a card and only one of X arrows shows up
