### ISSUE TITLE
Change options into a specific seed game

### ISSUE THREAD

**Issue by mmelwen** [Hanabi-Live/hanabi-live#2417]
When I tried to change the option "deck blind play" for the a gauntlet seed I got this warning 
![image](https://user-images.githubusercontent.com/66402571/148139710-40cafe6e-2237-4efa-b474-44dfb2c3ed45.png)
Is this the expected behavior ?

**Comment by Zamiell** [comment]
it's likely that changing options was never tested with "special" games that are created with an exclamation mark, so they are likely bugged.
in the meantime, just create a game with the correct options beforehand
