### ISSUE TITLE
/webpack-dev-server.sh does not make the browser reload after code changes

### ISSUE THREAD

**Issue by DrAnax** [Hanabi-Live/hanabi-live#2432]

**Comment by Zamiell** [comment]
i updated the client deps yesterday, so this probably has something to do with that

try to find out why this happens, if you are stumped you can always revert to the older version to see if that fixes the problem

**Comment by DrAnax** [comment]
![image](https://user-images.githubusercontent.com/2622043/148454852-1e676c8f-1882-4a5c-9218-61ffc6a429b1.png)

**Comment by Zamiell** [comment]
https://stackoverflow.com/questions/31602697/webpack-dev-server-cors-issue

?

**Comment by DrAnax** [comment]
Closed by #2443
