### ISSUE TITLE
the final page of full game history has a bunch of empty space

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#2454]
e.g.
- go to https://hanab.live/history/avanderwalde
- change number of games per page to 100
- go to page 23 (e.g. the last page)
- observe that there is a shitload of empty space before the footer

**Comment by DrAnax** [comment]
That's the behavior of the tablesorter. It reserves the space to avoid changing page height.

**Comment by Zamiell** [comment]
oh thats interesting

is that desirable? can that behavior be changed?

**Comment by DrAnax** [comment]
Desirable? I'd say so. I would expect a paginated table not to change height.

Avoidable? No idea

**Comment by Zamiell** [comment]
my original take is that it is undesirable, but i will defer to your judgement

**Comment by DrAnax** [comment]
> my original take is that it is undesirable, but i will defer to your judgement

Imagine having, say, 10 rows and a footer. The footer would move up on the last page of the table thus changing your page layout
