### ISSUE TITLE
Replays are not working - javascript error

### ISSUE THREAD

**Issue by mmelwen** [Hanabi-Live/hanabi-live#2456]
Uncaught TypeError: Cannot read properties of null (reading 'map')
    at GameMetadata.ts:30:37
    at text.ts:113:27
    at gameStateReducer.ts:150:20
    at immerClass.ts:78:58
    at e.produce (immerClass.ts:94:14)
    at immerClass.ts:78:17
    at stateReducer.ts:302:23
    at Array.reduce (<anonymous>)
    at Uc (stateReducer.ts:301:24)
    at stateReducer.ts:25:32

**Comment by mmelwen** [comment]
Try this one https://hanab.live/replay/693894

**Comment by iamwhoiamhahaha** [comment]
![error](https://user-images.githubusercontent.com/50160641/148635026-27dde528-fd4d-42be-8831-6805d74eed8a.png)

**Comment by iamwhoiamhahaha** [comment]
most of the replays not working it's like 1 in 3

**Comment by Zamiell** [comment]
i think its any replay where players voted to terminate the game

**Comment by Zamiell** [comment]
line 30 is this:
```ts
const playerNames = playerIndices.map((i) => getPlayerName(i, metadata));
```
so `playerIndices` is equal to null

**Comment by DrAnax** [comment]
Votes are not saved anywhere, therefore during replay there's an error when trying to display the final message.

**Comment by DrAnax** [comment]
> most of the replays not working it's like 1 in 3

Proof that democracy is bad
