### ISSUE TITLE
add localhost command to send everyone online a message + admin script

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#2460]

**Comment by DrAnax** [comment]
What's in the +admin script part?

**Comment by Zamiell** [comment]
for every localhost command i create a helper script that lives in the "admin" directory here: <https://github.com/Hanabi-Live/hanabi-live/tree/main/admin>

**Comment by DrAnax** [comment]
The "everyone online" part includes "general lobby" of discord prefixed with @everyone?

**Comment by DrAnax** [comment]
How about ie /message and /message-force (modals)?

**Comment by Zamiell** [comment]
"everyone online" refers to every user connected via websocket

the proposed feature is the same as this: <https://github.com/Hanabi-Live/hanabi-live/blob/main/server/src/http_localhost_send_warning.go>
except it sends it to everyone instead of a single username

**Comment by Zamiell** [comment]
it should be /sendWarningAll (because the existing command is /sendWarning)

**Comment by Zamiell** [comment]
the reason i want this is to alert when server is shutting down
