### ISSUE TITLE
"create a hypo to json exporter"

### ISSUE THREAD

**Issue by pianoblook** [Hanabi-Live/hanabi-live#2466]
^ title are the words that Zamiel used to describe what I believe was being discussed on Discord today.

I can try and describe the process I'm envisioning:

- Play through a hypo of a certain seed (on the website)
- Somehow create a permanent record of the hypo; Zam mentioned it may be possible to make it exportable it as a .json, which then could be shared + viewed by others.

And for those curious, the larger aim of this would be to aid in a large-scale data collection effort

**Comment by Zamiell** [comment]
the trigger would be to type `/copy` into the chat, or alternatively pressing some arbitrary key sequence

and then doing that would put the json in your clipboard

**Comment by pianoblook** [comment]
that sounds rad. 

I wonder if this could have simpler usecases - I could imagine it being useful for #con-questions, puzzles, and general discussion.
