### ISSUE TITLE
Add endpoint to allow viewing JSON data

### ISSUE THREAD

**Issue by DrAnax** [Hanabi-Live/hanabi-live#2499]
It could be either a GET to `/replay` with query var or a new POST to /replay

**Comment by DrAnax** [comment]
GET could be problematic, since in many cases there's a max character limit of 1024 in query variables

**Comment by Zamiell** [comment]
doesn't /export do this?

**Comment by timotree3** [comment]
/export allows you to go to a link and download JSON. We want a link that contains JSON that allows you to view a replay from that JSON.

**Comment by Zamiell** [comment]
for the purposes of giving someone a link so that they can link on it and view an arbitrary replay?
that's obviously not possible with a POST endpoint
so if its not possible with a GET endpoint, then we are probably out of luck

**Comment by DrAnax** [comment]
I managed to compress hypo JSON about 91-93%, reducing it from ~3k to ~200 base62 characters.

![image](https://user-images.githubusercontent.com/2622043/152667727-6a788fb8-77b6-4317-88e3-d506eb896e7a.png)

Further reduction can be achieved by creating a server side URL shortener, creating a final URL less that 10 characters long (but this will require a store, such as DB, File or Redis.

**Comment by Zamiell** [comment]
further reduction probably isn't needed?
