### ISSUE TITLE
pre-game showed incorrect max score

### ISSUE THREAD

**Issue by mmelwen** [Hanabi-Live/hanabi-live#2508]
https://hanab.live/shared-missing-scores/melwen/scharkbite/wump/MarkusKahlsen

the variant Pink-Ones & Gray (6 Suits)	

at pre-game screen showed that 2 of us actually had max score so pre-game score or missing page are incorrect

**Comment by DrAnax** [comment]
Can't reproduce that.

**Comment by mmelwen** [comment]
Neither did we
