### ISSUE TITLE
Allow changing of passwords

### ISSUE THREAD

**Issue by PlatinPython** [Hanabi-Live/hanabi-live#2511]
Currently the only way to change a password is via the password reset, which requires providing of personal information and an admin to approve it, which is logical for actual resets, but not if the goal is to simply change the password while still having access to the old password.

I would submit a PR myself, if it weren't for the fact, that I have little to no experience with neither TS nor Go, so I'm hoping that someone with more experience would implement this.

What I have in mind is basically the password changing form of other sites, providing the old password and the new password.

**Comment by DrAnax** [comment]
Other sites have a way to identify you. Here there's no personal identification (ie email address).

**Comment by Zamiell** [comment]
He's proposing that knowing the old password is the only requirement for changing the password.

**Comment by DrAnax** [comment]
Then perhaps with the old password and IP match we can make a password change page, how about it?

**Comment by Zamiell** [comment]
yes, that seems fine

**Comment by DrAnax** [comment]
Now that I'm thinking of it again, if the old password is correct, it's silly to match the IPs. One could simply login with the old password and override the stored IP address. Am I right?

**Comment by Zamiell** [comment]
yes you are right

**Comment by DrAnax** [comment]
Closed by #2528
