### ISSUE TITLE
suggested game settings

### ISSUE THREAD

**Issue by TheDaniMan** [Hanabi-Live/hanabi-live#2513]
When suggesting game settings to host in pre-game, timed option appears as timed: no, even if timer was suggested.

**Comment by DrAnax** [comment]
You mean like, the game was originally created as timed and when a guest pressed the Change Options button, the modal had the timed option unchecked?

**Comment by Zamiell** [comment]
it happened last night, i was playing with dani and i suggested a timed control, and then it said "No Timed" in the actual text that sent to the pre-game chat

**Comment by TheDaniMan** [comment]
I believe I originally had it as 2:00+0:15 and zam suggested 1:30+0:15. Even though the suggestion said timer: no, when I accepted the suggestion the timer was changed to 1:30+0:15 as intended.

**Comment by mmelwen** [comment]
The settings should reject Zam's timer proposal by default 😜

**Comment by Zamiell** [comment]
k ill close this then
