### ISSUE TITLE
Number of remaining possible clues rounded down in clue starved

### ISSUE THREAD

**Issue by TheDaniMan** [Hanabi-Live/hanabi-live#2519]
In clue starved, if you hover over the efficiency and look at Remaining possible clues: n, it will round down n to the nearest integer. This is probably intended and it is logically correct, but it is slightly worse for reviews and for planning future lost clues.

**Comment by vEnhance** [comment]
@Zamiell I would say this is actually a bug and we should just fix it?

**Comment by Zamiell** [comment]
sure i guess

**Comment by vEnhance** [comment]
oh I see the issue now lmao
