### ISSUE TITLE
Confirmation on twice skull

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2523]
Three possibilities:
1) always
2) add a message with a 'don't ask me again'
3) only if <Xgames

If it's not already the case.

**Comment by Romain672** [comment]
I would personnally goes into the 1) outside of speedrun.
It's not a button used a lot.

**Comment by Zamiell** [comment]
the whole point of requiring a double click is that there shouldnt be a confirmation

**Comment by Romain672** [comment]
I double clicked by accident/habbit today.
And not the first time i saw someone doing the same, maybe one or two others persons.

**Comment by mmelwen** [comment]
I don't like confirmation boxes, just press once is fine imo

**Comment by Zamiell** [comment]
ok

**Comment by Romain672** [comment]
I mean, melwen don't like 1. 2.
Since you was agressive on closing I suppose you are against to.

3 really don't look much annoying to do.

**Comment by Krycke** [comment]
I don't like confirmation boxes either, and i don't like option 2 or 3, as accidents happen even if you have played more than x games. But it's definitely a problem right now that players that want to cast a vote, accidently double click and terminate the game. Im not sure how to make this better, and until we have a good alternative solution we might just keep it as is.

**Comment by dartharaknus** [comment]
An auto accepting confirmation would work. Show a confirmation dialog with a timer of 5 seconds ticking down and a "Cancel" button.

* If the player doesn't cancel, it would terminate.
* If player terminated by accident, they can cancel.

**Comment by Zamiell** [comment]
in the 3 years since this issue was opened, we changed vote to be mapped to left click and termination to be mapped to right click.
thus, now termination basically never happens accidentally, which solves the OPs problem, thus the issue does not need to be re-opened.

**Comment by dartharaknus** [comment]
I've had people fearful of not having a confirmation for accidental right click. I am not sure how many accidentally did this but they were definitely afraid of it.

**Comment by Zamiell** [comment]
Given the following two facts:

1) it is very difficult to accidentally right click the skull
2) having to manually confirm a dialog box every single 

I am currently in favor of the status quo, although I am open to other solutions. Might want to open a new thread though since this one is quite old.

**Comment by dartharaknus** [comment]
I am fine with status quo too. Just one question:

> having to manually confirm a dialog box every single time that you want to terminate a game is infuriating

Show a confirmation dialog with a timer of 3/5 seconds ticking down and a "Cancel" button. I am wondering whether that's considered "manually confirming"

**Comment by Zamiell** [comment]
That is probably marginally better because it saves the user from doing an extra input, but still potentially annoying when you need to leave the game asap and now you have to wait for the countdown to finish

**Comment by dartharaknus** [comment]
> when you need to leave the game asap

As in, to start another game or leave the computer? Sorry, just find the UX discussion here interesting.

**Comment by Zamiell** [comment]
Like to start another game. It's common to terminate a bunch of times looking for a good opening hand. Also for speedruns and blitz games you are having to terminate the game almost constantly.
