### ISSUE TITLE
Broken link for Twitch emotes

### ISSUE THREAD

**Issue by NumerateClutter** [Hanabi-Live/hanabi-live#2525]
In https://github.com/Hanabi-Live/hanabi-live/blob/main/docs/FEATURES.md#chat, the "twitch emote" link leads to https://raw.githubusercontent.com/Hanabi-Live/hanabi-live/main/data/emotes.json. This link gives a 404. This is also true of the emojis link.

I'm not sure where it's supposed to lead. I searched the repository for "emotes.json" but couldn't find the file. Perhaps it was accidentally deleted or moved?

**Comment by DrAnax** [comment]
The client directories have been restructured and the file in question is now [here](https://raw.githubusercontent.com/Hanabi-Live/hanabi-live/main/packages/data/src/json/emojis.json).

**Comment by NumerateClutter** [comment]
Thanks for addressing this!

**Comment by Zamiell** [comment]
it's not actually there, that file lists the emojis
