### ISSUE TITLE
Improve empathy mostly in -Ones & -Fives

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2536]
In -Ones & -Fives variants, if a card can be limited at exactly one color OR one number, circle the color and the number.

Per example, in Rainbow & Omni-Fives, if a card receive the clue red and the clue yellow, circle the 'rainbow' and the 'five'.

**Comment by Zamiell** [comment]
in that situation, all of the other pips are removed, right?

**Comment by Romain672** [comment]
No, that card can be r5/y5/g5/b5/m1/m2/m3/m4/m5.
So you see all possibilities available.

**Comment by Zamiell** [comment]
does it remove the 2 pip, the 3 pip, and the 4 pip?

**Comment by Zamiell** [comment]
then we can't circle 1 and 5 because it can still be m4, thats confusing

**Comment by Romain672** [comment]
No because it can be m2, m3, and m4.
https://hanab.live/replay/710726#5 (omni-ones & omni): slot 2/3/4 can only be '1' or 'omni'.

**Comment by Romain672** [comment]
Here is what I think about, but it's small:
![empathy-fives](https://user-images.githubusercontent.com/12693191/151660408-c63054f0-b5d5-4db4-9068-88adf7f6de1f.jpg)

**Comment by Romain672** [comment]
Or else, here is an alternative view for the previous example, which I guess should require a button pressed:
![designx3](https://user-images.githubusercontent.com/12693191/153260304-9c87af9d-c797-4344-87de-47a1f7995b5f.jpg)

**Comment by Zamiell** [comment]
this would cause the client to lag too much, see the other issue where i did mockups

**Comment by Romain672** [comment]
But then, if you goes back to the initial subject, it look like the only thing I want is like the orange number on this turn: https://hanab.live/replay/710726#25 , a way to tell that x color has been clued.
And this seem to not create lag.

So only for Muddy Rainbow, Muddy Rainbow, Rainbow, and Omni when the card was clued with a single color.

**Comment by Zamiell** [comment]
its some issue about putting more information on cards

**Comment by DarthGandalf** [comment]
link pls

**Comment by Zamiell** [comment]
https://github.com/Hanabi-Live/hanabi-live/issues/864

**Comment by nitawa-hl** [comment]
Could something like tracking negative clues work for this? I had this idea (mostly for brown, but could apply here) that colors the negative information of cards as one does with positive information for pink (with a different color than the used for positive info), ie, in a Brown game, when a clue 3 is given, all non-touched cards get a colored 3 to indicate that it can only be 3 if it's brown. Similarly, for pips one might be able to change the opacity of the pip?

**Comment by Zamiell** [comment]
i dont follow

**Comment by Zamiell** [comment]
like a brown border around the number 3?

**Comment by Zamiell** [comment]
if so, that sounds cluttery and terrible

**Comment by nitawa-hl** [comment]
No, changing the font color of the rank pip to, for example, green, the same way that in a Pink game, you mark positive information by changing the font color of the rank pip to red/orange.

**Comment by Zamiell** [comment]
not a huge fan, if all the number pips are different colors it becomes confusing and hard to tell at a glance what the pips are showing

**Comment by Zamiell** [comment]
having them be either white or yellow seems like a pretty good compromise

**Comment by nitawa-hl** [comment]
Not sure I understand what compromise you're suggesting, but if I'm not mistaken a card can't have both positive and negative rank information, since having positive information makes it not pink and having positive information makes it not brown, so it would always have at most 1 color

**Comment by Zamiell** [comment]
the compromise is between
1) having pips be all white and show no additional second-order information
2) having pips do X and show some additional second-order information

**Comment by Romain672** [comment]
I tried to make red bigger, here is 110%, 120%, 130%, 140%, and 150%:
![big](https://user-images.githubusercontent.com/12693191/153282671-0eda46e2-c2f5-42f6-ae16-535e0ab15d84.jpg)

(sorry for bad display, it saved wrongly)
It look like to me 120% look fine if you want to just tell which color has been clued (because on variants like 'Muddy Rainbow-Fives', a red clue should make that card more likely to be red).

**Comment by Zamiell** [comment]
seems like a duplicate of #1039

**Comment by Romain672** [comment]
If we goes into that, yeah it's duplicate, i will post it there.
