### ISSUE TITLE
Critical Four & Critical Three (6 Suits)

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2543]
Weird this hasn't been proposed before.

**Comment by vEnhance** [comment]
imo it's too many critical cards, since each suit is now
1 1 1 2 2 3 4 5
so you lose 1 in 4 deals outright without bottom deck blind play

**Comment by Romain672** [comment]
Yeah right it's -12 in 6 Suits. I though it was -10.
