### ISSUE TITLE
Join a game as hydra head

### ISSUE THREAD

**Issue by DarthGandalf** [Hanabi-Live/hanabi-live#2567]
When playing as hydra, a player needs to join as spectator as some other player, but without seeing that player's hand before switching view to that player's view. This is very hard to do without accidentally seeing the hand.

UI may look like this:
![Выделение_408](https://user-images.githubusercontent.com/325092/152459076-15eb8e94-e503-4ed1-ba4b-99ca1d806cf4.png)

**Comment by Zamiell** [comment]
how does the ui appear

**Comment by DarthGandalf** [comment]
on the click on the button on the right. The button in my mock is barely visible, but it's on the right edge of the green rows

**Comment by Zamiell** [comment]
so you are adding a button to every green row?

**Comment by timotree3** [comment]
Here's how I do hydra without this feature
1. Hover my mouse over the game
2. Close my eyes
3. Click the game
4. Hold spacebar
5. Open my eyes
6. Right-click the player I want to spectate as

**Comment by Zamiell** [comment]
goated

**Comment by DarthGandalf** [comment]
@Zamiell what's your suggestion?

**Comment by Zamiell** [comment]
are you are adding a button to every green row?

**Comment by DarthGandalf** [comment]
yes

**Comment by Zamiell** [comment]
playing as hydra is a niche, rarely used feature.
ui space is valuable, and i hate clutter.
so we have to determine if adding a button to every single green row is worth it for the one in one thousand people who will actually click that button, and if there are any other alternatives that could be better

**Comment by DarthGandalf** [comment]
another way to get the same menu is right click on the row, then it doesn't need a new button

**Comment by Zamiell** [comment]
i like that better, but it has some downsides:
1) you remove the natural right click context menu, which users might legitimately want to appear when they right click something
2) its not mobile friendly

**Comment by Zamiell** [comment]
for this reason, i think for most websites, adding custom right click context menus is frowned upon.
(on the other hand, we already do it in-game inside the canvas element, but i think that is a bit different)

**Comment by DarthGandalf** [comment]
proper browsers let users get the native context menu regardless of what the website does, by holding some button. For example, Shift-rightclick in Firefox.

**Comment by Zamiell** [comment]
right, but many users may be be aware of such a hotkey, and they might be annoyed/mad if they intended for the vanilla context menu to appear in the first place

**Comment by DarthGandalf** [comment]
but yes, this is why I suggested a separate button first, which is also more mobile-friendly

**Comment by DrAnax** [comment]
Mind that spectators row is not visible on mobile, portrait

**Comment by DrAnax** [comment]
Why not hyperlink the players names instead? This might require a cursor change as well, to make it more obvious

**Comment by Zamiell** [comment]
seems fine
