### ISSUE TITLE
lint_client.sh should probably prettify/lint/prune data/src as well

### ISSUE THREAD

**Issue by DrAnax** [Hanabi-Live/hanabi-live#2578]

**Comment by Zamiell** [comment]
i dont think build_client lints anything, right?

**Comment by DrAnax** [comment]
meant lint_client.sh

**Comment by Zamiell** [comment]
yeah, submit a PR for that

**Comment by DrAnax** [comment]
1- `eslint` complains about two files
- warning: `createVariantsJSON.ts` has two unused functions (will be fixed in a PR soon)
- error: `version.js`
> Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
> The file does not match your project config: src/version.js.
> The file must be included in at least one of the projects provided

how to fix the problems with `version.js` ?

**Comment by DrAnax** [comment]
2- fixed via .eslintignore
