### ISSUE TITLE
Feature Request: "Perfect or Bust" option

### ISSUE THREAD

**Issue by glassbead0** [Hanabi-Live/hanabi-live#2585]
Note: this is different than the "All or Nothing" option.

**Context:**

Our group often plays with the intent to get a green checkmark for a particular variant (so we disable "bottom-deck blind-plays"). Whenever we discard (or misplay) a critical card, or our pace goes negative, thus making a perfect score impossible, we terminate the game and start over. Since we're only playing for perfect scores, we sometimes get bottom-decked with a 3 or a 4 (for example r4), meaning that as soon as the first r4 was discarded, a perfect score was impossible, we just didn't know it yet, because the other r4 was on the bottom.

**Feature Request:**

For a particular game, allow a "Perfect or Bust" option (or come up with a different name). When "Perfect or Bust" is enabled, if the bottom card is a 2, 3, or 4, and the other copy of the bottom card gets discarded (or misplayed), a notification (or something TBD in the UI) should alert the user that a perfect score is impossible (thus allowing players to terminate the game if they want).

**Additional Thoughts:**
- I suppose the logic should apply to 1's too, if two 1's of particular color are discarded, and the third 1 is the bottom card, a perfect score is impossible. (some variants, like up-or-down, would not need the 1's logic).
- There are of course many other conditions which make a perfect score impossible, despite being unknown to the players... eg: some deals are impossible from the start even with perfect play (eg: all 1's on the bottom), or the last few cards to be played are in a bad order in players hands...etc, but I'm not proposing any sort of logic to determine all possible situations where a perfect score is impossible, only the bottom-deck situation.
- I know it feels "dirty" to have the code "look" at the bottom card, and perform a certain action based on how the game plays.... but I believe this would make it more enjoyable for anyone chasing green checks... so that we don't spend time playing through a game that cannot be won.

I'm curious if others would like to see this feature.

**Comment by glassbead0** [comment]
I want to also add that I know there are conventions that reduce the probability of getting bottom-decked... eg: 3-bluffs, chop-moving 3s and 4s...etc, but I don't think that should be an argument against allowing this feature. It's not always possible to save 3s and 4s, even with all of the conventions, and of course, different groups play with different conventions.

**Comment by Zamiell** [comment]
i dont like adding extra options to the website, so a small thing like this doesn't meet the criteria of being useful enough to warrant adding to the site
