### ISSUE TITLE
get rid of all of the "<span class="red">Error</span>"

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#2587]

**Comment by DrAnax** [comment]
You mean the entire function [here](https://github.com/Hanabi-Live/hanabi-live/blob/b07d8aaae8ad3c0f69c5393d07a7545fd64f3e1e/packages/client/src/chat.ts#L719)?

**Comment by Zamiell** [comment]
is everything currently using that function? if so, i'll close

**Comment by DrAnax** [comment]
Yes, plus 3 more for PMs, [here](https://github.com/Hanabi-Live/hanabi-live/blob/b07d8aaae8ad3c0f69c5393d07a7545fd64f3e1e/packages/client/src/chat.ts#L514) (also lines 516 and 530) used to mark the sender of the PM and the Server Notice.
