### ISSUE TITLE
Add two new colors for frames (clued + [f] and clued + [cm])

### ISSUE THREAD

**Issue by nitawa-hl** [Hanabi-Live/hanabi-live#2591]
Usually, when a card with a f or cm note is clued, the colored frame becomes just orange. Sometimes that can cause mistakes, so I suggest that in those cases the frames are colored differently (for example dark blue for [clued,f] and yellow for [clued,cm]?).

**Comment by Zamiell** [comment]
we haven't done that because that introduces unnecessary complexity.
i dont want to make users have to memorize what a ton of different borders mean.
having 3 different borders is a good compromise
