### ISSUE TITLE
Should hydra head spectators see morphed cards according to they player's notes?

### ISSUE THREAD

**Issue by DrAnax** [Hanabi-Live/hanabi-live#2595]
I'm spectating Alice and she writes the note "y1" on a slot. Should I see it as <any> or as Yellow 1?

**Comment by Zamiell** [comment]
Since you can have independent notes from Alice, then I think no it should not morph

**Comment by DrAnax** [comment]
There's two points of view here, depending on why I chose to spectate the game as a player.

Case A: I'm trying to get better. I let Alice play, watch here moves, notes etc and ask her

Case B: I'm watching the game via Alice because I find it more exciting to have the information hidden.

In the first case, I would certainly like to have the cards morphed and ask her why she wrote the note. In the second, maybe I just want to have my own notes.

Perhaps the best of both worlds would be to have the cards morphed by Alice's notes and overridden by the spectator's notes?

**Comment by DrAnax** [comment]
By the way, the player's notes shadow the spectators' in a peculiar way:

- Alice notes "y1"
- Spectator notes "yellow"
- The card does not morph
- Card tooltip reads "y1"
- Note editing shows "yellow"

**Comment by Zamiell** [comment]
I t hi ink it would be distracting as a spectator to just all of a sudden have a card morph suddenly
