### ISSUE TITLE
Odds&Evens: don't highlight pips 1 and 2

### ISSUE THREAD

**Issue by DarthGandalf** [Hanabi-Live/hanabi-live#2598]
1 and 2 are highlighted with orange like on pink variant; but with O&E all odd numbers are equal, number 1 shouldn't be any special.

**Comment by nitawa-hl** [comment]
This should be fixed with my last PR #2590

**Comment by DarthGandalf** [comment]
ah cool, thanks. Haven't checked that var today since the server restart
