### ISSUE TITLE
Right click on card and stacks in replay does not show the yellow arrow anymore

### ISSUE THREAD

**Issue by Lel0uch-H** [Hanabi-Live/hanabi-live#2602]
Is this an intended recent change?

**Comment by Zamiell** [comment]
no, takis do you want to take a look

**Comment by DrAnax** [comment]
It works in shared replay, it doesn't in private replay.

Reminder: before #2596 the shared-replay link would turn into a private replay link. Maybe that was the reason behind the issue?

**Comment by DrAnax** [comment]
It was always like this. OP (P = programmer) probably didn't think of a reason to have arrows shown when solo viewing a replay.
