### ISSUE TITLE
Support more suits

### ISSUE THREAD

**Issue by DarthGandalf** [Hanabi-Live/hanabi-live#2606]
e.g. BGA supports 7 suits

**Comment by Zamiell** [comment]
bga sucks though

**Comment by rogers-j** [comment]
Seven suits really does seem like too many. There aren't any official printings of the rules that call for that many, are there?

**Comment by Romain672** [comment]
Rainbow+Black powder is on bga.
I believe that's official? Can someone confirm.

**Comment by DarthGandalf** [comment]
black powder is official, yeah. They just combine all the existing suits in one game. That is, 5 normal suits, rainbow, and the black powder (aka white reversed)

**Comment by DarthGandalf** [comment]
> bga sucks though

it does, however this is one place where we're the ones missing feature

**Comment by rogers-j** [comment]
https://rnrgames.com/Content/RRGames/images/productrules/Hanabi_BlackPowderExpansion_rules.pdf is clear about the new suit being the _sixth_, not seventh

**Comment by Zamiell** [comment]
> we're the ones missing feature

i dont think adding unfun, stupid features purely for the sake of adding "missing" features is worth it

**Comment by Zamiell** [comment]
its the same reason i deny most of the variant requests i get

**Comment by vEnhance** [comment]
Closing this as wontfix since it doesn't seem like there is much interest for having more than six suits, I also agree 7 seems too many

Feel free to re-open comment if you want to make a case for 7+ suits
