### ISSUE TITLE
Create duplicate of existing variants

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2613]
"White & White (X Suits)"
"Brown & Brown (X Suits)"

For all colorless suits, there seem to have no problem.
For Brown and Pink, that's problematic. I would suggest to said that "Brown & Brown" each have their own color and "Ambigious Brown" share the same brown color.

**Comment by Zamiell** [comment]
not for now

**Comment by Romain672** [comment]
Would a suit which copy the rightmost special suit be better and possible?
