### ISSUE TITLE
Inappropriate license change

### ISSUE THREAD

**Issue by DarthGandalf** [Hanabi-Live/hanabi-live#2625]
bddce95c97a427ff079ed7064362a2edf643dd6c changed license of the project from GPL to AGPL without getting permission of all the copyright holders.

Section 13 of GPLv3 allows using the GPL-licensed code together with AGPL code, but doesn't allow changing the license completely.

It is possible to change license, but that's not how you do it.

Please revert.

**Comment by Zamiell** [comment]
can you submit a PR
