### ISSUE TITLE
mistake in stats?

### ISSUE THREAD

**Issue by olevino** [Hanabi-Live/hanabi-live#2628]
sitting in "no variant" pre-game table, i saw that i have 19 total games and 27 games of this variant. Looks like a mistake..
<img width="303" alt="image" src="https://user-images.githubusercontent.com/32940100/168446335-04e3c052-3778-46f1-99eb-9e9ac2537bec.png">

**Comment by vEnhance** [comment]
So @Zamiell is there a reason why we include terminated games in the "of this variant" but not under "total games"? It's always felt like we should be more consistent about this.

**Comment by Krycke** [comment]
Do we want terminated games to be included in both cases, or excluded?

**Comment by Zamiell** [comment]
excluded
