### ISSUE TITLE
Give the lead when you double clicking the crown (and the leader of the game is away)

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2642]
Initially I wanted only if the leader was away, but if all players don't abuse of it, that's even better in most cases.
Don't let spectators use that functionnality.

I guess even in important games, if someone abuse of it, he will just not be invited anymore next time, so that should work.

**Comment by DarthGandalf** [comment]
This functionality is already available (and abusable) via the `/setleader <name>` command, so adding a GUI way to do the same would be nice

**Comment by Romain672** [comment]
Yeah, we tell me it after.
I tried to right click on it too, expecting maybe the same window open if I was leader and I was giving the lead to someone else.
