### ISSUE TITLE
Firefox: opening a link with a twitch steam open crash Firefox

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2644]
Title:
 - open a twitch stream
 - pause the stream
 - open any link like https://hanab.live/replay/794484#6
 - see the firefox navigator being black

Not sure what cause that bug.

**Comment by DarthGandalf** [comment]
If browser crashes, that looks like a browser issue

**Comment by Romain672** [comment]
I think it was a problem from mozilla, and it look like they resolved it.

**Comment by Romain672** [comment]
I will close, that didn't happen again. I think it was coming from Firefox.
