### ISSUE TITLE
Up or Down with dark suit

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2650]
Hi,
Dunno why this hasn't been done.

Up or Down (6 Suits) remove 6 cards from the deck.
A dark suit with Up or Down should get the cards S12345, which remove 4 cards from the deck.
6+4=10, it's like any double dark, so work with 6 Suits.

**Comment by vEnhance** [comment]
Zam can you assign to me?

**Comment by Zamiell** [comment]
this is intentionally not implemented because it violates the efficiency limits

**Comment by Romain672** [comment]
I don't understand though. (read again my first post)
Is it because Up or Down is coded on a way were a dark suit would be hard to code?
