### ISSUE TITLE
Known Unplayable card warning can display incorrectly in Hypo after editing cards

### ISSUE THREAD

**Issue by calvinballing** [Hanabi-Live/hanabi-live#2656]
In the example below, the multi 3 was originally a different card, but was edited in the hypo to be the multi 3.

The multi 3 should be playable, however, the `Are you sure you want to play this card? It is known to be unplayable based on the current information available to you. (e.g. positive clues, negative clues, cards seen, etc.)` warning appears unnecessarily.

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/5534029/183797023-3f552fdf-472d-4676-8af7-b03dd02ae7da.png">

Here are two possible suggestions for different ways to address this scenario:
Suggestion 1) Make the logic for this alert work correctly for edited cards
Suggestion 2) Turn off this alert entirely when in hypos

**Comment by Krycke** [comment]
This will only happened if you have known information about a card, and then edit the card into something that contradicts that knowledge. Now, after the "edit card"-modal update, it is harder to make these contradictions by mistake, and if you do it on purpose, then I think it's ok that this alert shows up.

**Comment by jack67889** [comment]
Haven't been able to reproduce this in a while, but always when it did happen the hypo got stuck after the message. The card you tried to play just floats there and you can't go back or forward a move, so you're forced to exit the hypo.

**Comment by Krycke** [comment]
It can still happen, but you need to be on 2 strikes for it to appear. Just create a hypo, make 2 strikes, clue someone an unplayable 5, and try to play it, then it will appear. Change the card to a playable 1, and it will still appear. Of course it can't be a 1, as it has positive 5 on it, but this is when it can happen. 

About the stuck floating cards. You can drag any other card to a non valid position, and it new card and the stuck card both will tween back to it's original positions.

**Comment by Zamiell** [comment]
just disable this popup message when inside a hypo

**Comment by Krycke** [comment]
Yeah we can, That's easy, But I thought it was a feature that it was there. You decide

**Comment by jack67889** [comment]
> About the stuck floating cards. You can drag any other card to a non valid position, and it new card and the stuck card both will tween back to it's original positions.
Ah yes, I see now. But you can only drag the card when it's the turn of that player. So I guess I tried to move back a turn and then the card gets stuck, because it was the turn of a different player.

**Comment by Zamiell** [comment]
> But I thought it was a feature that it was there.

the point of the feature is to prevent a bomb in a real game, if you bomb in a hypo then its trivial to click "back" and redo the move
