### ISSUE TITLE
During review, add the turn one note have been added

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2659]
It can be like "**Romain672** (10, 25): useful? | [cm]" to said that this note has been edited during turn 10 & 25.

Even if the note is about the turn 8, and Romain writed the "useful?" in turn 10, it will be writed 10, but since it's close, you can in review pretty easily do the link.

On my new system, I have some chop moved card from the left, and so it's pretty hard to remember which card have been chop move in mid game and which card haven't, since sometimes the first three slots of someone has been chop moved at differents moments of the game.

And maybe if it has been edited more than 5 times, do a special thing like "**Romain672** (10, 25, 26, 30...): useful? | [cm] | r2? [cm] | nope what is this [cm] | look like y4 [cm]" but even though that could be fine to have all turns without exception.

**Comment by GuolinM** [comment]
+1

**Comment by Zamiell** [comment]
we decided against this already, see the past issues
