### ISSUE TITLE
Smaller pseudos in note

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2660]
And why not display only the first three characters of each pseudo? like "**Rom**: useful? | [cm]".

I guess the "who_nabi_06" should be rename into "06_who_nabi".
But then you could need to do something if two players have the same characters. Maybe add a special sign at the start of the pseudo depending of which player goes first?

**Comment by Zamiell** [comment]
i dont know what a pseudo is

**Comment by Krycke** [comment]
The suggestion is to just not print the fill length of the players names in the notes, and cut them off after the characters (with a number to differentiate them.

**Comment by Zamiell** [comment]
there's a 15 character limit on usernames so i dont see this as worth doing
