### ISSUE TITLE
Turn based?

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2668]
Hi,
I just run accross a person on bga who would want turn based on .live.
So a way to play one turn every 3 hours / 1 day.

**Comment by BowTieBird** [comment]
This gamemode is commonly known as "Correspondence" in the chess world

**Comment by Zamiell** [comment]
we already decided against this for now

**Comment by vEnhance** [comment]
@kimbi mentioned this idea as well to me, so making a note here for posterity
