### ISSUE TITLE
Keep spectator notes

### ISSUE THREAD

**Issue by mgs2176** [Hanabi-Live/hanabi-live#2672]
Is it possible to keep spectator notes? Would like to see if any specs make any comments - might learn from it. Could be temporary or not, but at least labeled spec: or italicized or somehow differentiated from player notes.

**Comment by Krycke** [comment]
This can be closed

**Comment by Zamiell** [comment]
yep, thanks to krycke for this

**Comment by Zamiell** [comment]
btw krycke you can put "Closes #2672" in your PR and it will automatically close the issue when i pull the PR

**Comment by Krycke** [comment]
Well almost. I wrote "Closes issue 2672" and that did not seem to work.

**Comment by Zamiell** [comment]
yeah you have to denote it with the #

**Comment by argothiel** [comment]
Is this related to breaking the HTML characters in the comments?

![image](https://user-images.githubusercontent.com/13932353/202674791-dfc42458-e7a5-448a-88c8-c69771edc7b1.png)

**Comment by Krycke** [comment]
I'm guessing not this one, but probably the patch that change what was actually html escaping. That patch just made the current code actually work, but maybe that code was wrong?
