### ISSUE TITLE
Button to pull players into lobby instead of restart

### ISSUE THREAD

**Issue by chennisden** [Hanabi-Live/hanabi-live#2673]
Currently if I'm playing with Bob, Carol's spectating, and we want to play 3p together, the only way to do this is to leave the game and start a new lobby. Instead we could just have Carol join the lobby (and keep Alice/Bob)

And then let's say Alice Bob and Carol are playing Variant A. Then they win and want to move onto Variant B. Would be nice for QOL if they could just be sent to the same lobby (especially if they're playing with a password), and then they can change the variant from there.

**Comment by GuolinM** [comment]
Big +1

You could argue that you could just create a new lobby, but it does add unnecessary friction for every single person in the lobby. Also,

**Comment by Romain672** [comment]
The main thing is if Bob is afk.
That should be done with vocal, and in worst case, it's a quick abandon, but I think you can work around it.

On quick solution would be to ask in chat for everyone one '+'. And that just work without dev time, that let you see potential afks.

**Comment by vEnhance** [comment]
I actually implemented this a couple years back, but it never got merged:
https://github.com/Hanabi-Live/hanabi-live/pull/1961
I guess since it got brought up, I'll bring the PR up to date

**Comment by vEnhance** [comment]
@Zamiell I think we can close this now #1961 is merged and #2683 has been entered?

**Comment by Zamiell** [comment]
indeed i will close it
