### ISSUE TITLE
Feature requests for remake table

### ISSUE THREAD

**Issue by vEnhance** [Hanabi-Live/hanabi-live#2683]
- [ ] [Manage specs](https://discord.com/channels/140016142600241152/333680903748321282/1027655997164113960)
- [ ] [Preserve game password](https://discord.com/channels/140016142600241152/733076625079402647/1027705966503919697)

(@Zamiell you can assign to me)

**Comment by Krycke** [comment]
Just read the comments in discard for this issue. Specs might not want to upgraded to players, and also if the lobby if password protected that might not be good at all. Maybe give them a dialog option "the table if restarting, do you want to join as a player or spectator"? (Unless it's password protected)
