### ISSUE TITLE
New Variant Proposal: Funnel Colors

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [Hanabi-Live/hanabi-live#2695]
#### Funnel Colors
- Red cards can only be touched by red clues.
- Yellow cards are touched by red and yellow clues.
- Green cards are touched by red, yellow and green clues.
- Blue cards are touched by red, yellow, green and blue clues.
- Purple cards are touched by red, yellow, green, blue and purple clues.

**Comment by Romain672** [comment]
https://github.com/Hanabi-Live/hanabi-live/issues/2516

**Comment by vEnhance** [comment]
From a software perspective this would actually be pretty easy to implement.

Color name proposals:

![image](https://user-images.githubusercontent.com/3750940/200841350-90cfdf49-de33-4671-ac90-7bced1fd1573.png)

**Comment by vEnhance** [comment]
@Zamiell  can you assign to me?

But going to wait until after holiday mix gets merged to avoid variant ID conflict

**Comment by Zamiell** [comment]
ok

**Comment by iamwhoiamhahaha** [comment]
That's awesome! Thank you @vEnhance
