### ISSUE TITLE
Show allPossibiltiesTrash in the UI

### ISSUE THREAD

**Issue by vEnhance** [Hanabi-Live/hanabi-live#2709]
e.g. auto-add the trash icon

**Comment by Zamiell** [comment]
sure

**Comment by Zamiell** [comment]
on the other hand, right now the trash icon is gated behind a note, i think it would be disruptive to auto show it without the user doing anything explicitly
(it would be auto appearing on many cards)

**Comment by vEnhance** [comment]
How would you feel about a small trash can icon in

- the upper left corner for backs of cards,
- the lower left corner for fronts of cards.

Location coincides with the blue questions marks in DDA, but these situations are mutually exclusive.

**Comment by Zamiell** [comment]
that might be fine, can we see some screenshot examples to show off how intrusive (or not) the new icons would be?
as a word of warning, historically, whenever we make a change of this nature, people always hate it =p

**Comment by vEnhance** [comment]
![image](https://user-images.githubusercontent.com/3750940/201479126-cf495136-5410-4439-8b7c-94e824dee96c.png)

(both g3's are dead so the trash can on t2's g5 is correct)

**Comment by Zamiell** [comment]
when it is that small, it is pretty hard to make out that it is actually a trash can, so my gut reaction is that i don't like it.
the critical icon is easy to see because it is a simple shape that has a fill.
perhaps we need an icon similar in design, which would also satisfy the design goal of having a congruent UI.

**Comment by vEnhance** [comment]
That's fair.
If you have a different icon you want me to try, I'm happy to do so.
Otherwise I'll go look for a darker/simpler one

**Comment by Zamiell** [comment]
> If you have a different icon you want me to try, I'm happy to do so.

i'm open to suggestions

![image](https://user-images.githubusercontent.com/5511220/201479804-47f8d1e4-6a09-4d6b-a19a-4e9431538da3.png)

**Comment by Zamiell** [comment]
![image](https://user-images.githubusercontent.com/5511220/201482905-dc8e4d4a-07f6-41d9-b38e-8ea5bd0d0554.png)

**Comment by vEnhance** [comment]
https://icons8.com/icon/87385/waste maybe?

**Comment by Zamiell** [comment]
Much better imo
