### ISSUE TITLE
Rename 'Dual-Color (6 Suits)'

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2713]
Hi,
Following what I said in #2381 , 'Dual-Color (6 Suits)' is really not a good name.
It look like it will be 'ab bc cd de ef af' in colors of suits, to follow any other dual color variant, but in reality it's 'ab ac ad bc bd cd'.

I would propose:
 - 'Dual-Color 4 Colors (6 Suits)', adding 4 colors insist on the fact the variant is weird, which is nice since it's the only dual color variant like that
 - 'Trio-Color (6 Suits)' since in reality every color touch 3 Suits

**Comment by vEnhance** [comment]
"K_4 Colors" 😇

**Comment by vEnhance** [comment]
So do people have actually more serious suggestions for names?

**Comment by vEnhance** [comment]
The more I think about it, the more I feel like a name change is still confusing and also makes the code harder to maintain. For instance, `Trio-Color` would mean we need to edit `isDualColor` function in the client.

So, I'm going to make a simple PR that just documents the suits in `VARIANTS.md`, and leave it at that.

We can re-open this I guess if someone finds a convincing name that gets reasonable support.
