### ISSUE TITLE
[Feature] Remove unwinnable seeds

### ISSUE THREAD

**Issue by Krycke** [Hanabi-Live/hanabi-live#2717]
It shouldn't be hard to calculate if the seed of winnable at all, with the current player count. Say a bottom decked black 1 or a double bottom decked 2 in a 2 player game.

We could just remove those seeds completely to not have to kill the buzz after a long perfect game of a hard variant.

**Comment by Krycke** [comment]
I guess you can also make an option "kind seed" which assures that at least one 1 of each color is in the top half of the deck, and at least one 2 of each color is in the top 2/3 of the deck, or something

**Comment by Romain672** [comment]
Bottom deck blind play do that for most cases already.

While I think it would be a good idea, you should think of the long term.

Per example, let's take speedrun.com: https://www.speedrun.com/hanabi?h=2-Player-5_Suits&x=jdz37l32-dloy6d8o.gq7kgy1p . I don't think there is any critical suit on there, so it seem fine, but that would mean the hanabi game with critical suit is not anymore possible to do in real life.
A good part of video game speedrun can have an rng check: if you are lucky, you can goes on on your run. If you are unlucky, you need to restart the run.

Another problem is that if you assume you play two games of hanabi where a critical discard is forced, it can be either r3 or b3. And r3 is at the bottom. So the team which play with r3 discard will lose, while the team with b3 will win. This situation is rarer, but it will still happen. I still understand how this situation is different than your proposal though.

So I didn't find any strong counter argument to it, but maybe I'm missing some.

**Comment by Krycke** [comment]
Of course this will not prevent a team to be unlucky. And that is not the meaning. But some seeds you can quite easily determine that they can never be won, no matter the convention, no matter your luck in the rest of the game. And those are the games I'm talking about, that if we want, we could just remove.

**Comment by Zamiell** [comment]
we already decided that we are not going to pre-rig the decks to be winnable by default.
(we should not impose our normativity on others, i've written about this in the past)

as for a table option, i am categorically opposed to more table options unless they meet a relatively high bar of usefulness/utility, and i'm not sure if this one would meet that bar
(especially because using it would result in a red x on your max score in the same way that bottom deck blind play would, which would probably prevent people from using it)

**Comment by Krycke** [comment]
Yeah I guess that is true. Well I thought I'd surface the thought when I got it.
