### ISSUE TITLE
Title / Description rework

### ISSUE THREAD

**Issue by Romain672** [Hanabi-Live/hanabi-live#2733]
Hi world,
Atm the title text is limited around 44 characters.
This is pretty few it's hard to note which convention you are using if it's not a well known one.

And we got no description of the table. We don't even see the settings in the main page.
I agree that some of the settings are not useful (like it seem bottom deck blind play), but some others look really important (like detrimental characters).

**Comment by Krycke** [comment]
How about a question mark icon or similar somewhere (in front of the variant text?), and if you hover the icon, a tooltip shows up with all the options?

**Comment by Krycke** [comment]
Maybe in-game as well. Now I don't see a way in-game to display which options are actually on, and the title of the game is not visible either. I don't know where to put in though? In the same tooltip as other information when hovering the deck?

**Comment by Zamiell** [comment]
seems fine
