### ISSUE TITLE
Globally known card inferences should hide colors/numbers rather than show X elimination markers

### ISSUE THREAD

**Issue by shemetz** [Hanabi-Live/hanabi-live#2734]
Example scenario:
- purple 3 has been played
- other purple 3 has been discarded
- a player has a card in their hand which was clued as a 3, and negatively clued as not yellow or blue
- currently the website would show this card as "3, red or green, with purple eliminated due to inference"

I think that instead of showing the "purple 3" option as eliminated due to inference, it should be completely gone (just like the blue/yellow options in this case).  Alternatively, it should be marked as eliminated in some other way (white X? blacked-out digit?).

The problem is that at the moment, **removed digit/color markers are determined by clue information only** (what you were or weren't directly clued) while **black X inference markers are determined based on all other cards seen by the player (you)**.

However, in practical use, the reason we want the black X inferences to be marked differently than removed digits/colors is because players know different information about the state of the game, and we want to make it clear to the user that even though they know some negative information, other players don't know it and should not be predicted as if they do.

Therefore, **the goal of black X inference markers is to point out personally inferred information which is not obviously known to all players**, and this conflicts with their current behavior because it also points out globally known information:  cards already played and already discarded.

So, I'm asking for this type of info to be distinct.

Practically, I think it should just be lumped in with the hidden ranks/colors on cards (e.g. removing the yellow color after a Yellow hint does not touch the card).  That is, if all copies of a card are in the discards or on the board, that card should be completely removed as a possibility within unknown cards (rather than marked as an inferred impossibility).  This is my opinion because I don't think any game strategies are based on the difference between negative clues and negative inference from discards/plays.  However, if this distinction still matters to someone, you can add a third type of marker.

Screenshot containing example:
![image](https://user-images.githubusercontent.com/6516621/205687945-d0078234-6680-46a1-aca2-ec992b3bd46f.png)

**Comment by Zamiell** [comment]
i like the current delineation between "information from positive/negative clues" and "information from other things".
i think that this specific delineation results in the clearest UI for the end-user, as it is simple and easy to understand.

> Therefore, the goal of black X inference markers is to point out personally inferred information which is not obviously known to all players

that is incorrect, the goal is to point out inferred information which is either globally known to all players or known only to a subset of players.
i don't deny that a new delineation between a "globally known inference" and "non-globally known inference" could be useful, but i dont think it is worth the other tradeoffs

**Comment by shemetz** [comment]
To me it seemed the opposite actually - it's simpler and easier for me to understand that a missing color means "everyone knows this isn't purple" while a crossed-out X means "I know this isn't purple, but maybe others don't".  And in practice, this is the difference that matters for gameplay choices.

We could discuss this more (or see what others think) - but, maybe this could be a toggled setting?

**Comment by Zamiell** [comment]
i am allergic to toggled settings, so probably not

**Comment by shemetz** [comment]
Could I feasibly edit my own client code (with extension or script or manually) to get this behavior?

**Comment by Zamiell** [comment]
probably, it would be a pain to keep it up to date though with every new commit to the main repo
