### ISSUE TITLE
Shadowing and then joining bugged.

### ISSUE THREAD

**Issue by Stuurrm** [Hanabi-Live/hanabi-live#2749]
If you shadow somebody in the lobby and then join the game as a player your perspective will be of the person who you shadowed. In additon sometimes you will not be able take any action.

**Comment by Krycke** [comment]
Oh, interesting edge case. Thanks for reporting

**Comment by calvinballing** [comment]
We also had this happen in one of our games for the first time today

**Comment by DarthGandalf** [comment]
I had this today, by accidentally clicking someone's name when trying to join the table, then leaving and rejoining as a player.

This is my turn, and I'm not able to do anything:
![Выделение_442](https://user-images.githubusercontent.com/325092/208319199-e13ffa12-0f16-4176-9e1f-1d737a67aca3.png)
