### ISSUE TITLE
Consolidate seed history pages

### ISSUE THREAD

**Issue by vEnhance** [Hanabi-Live/hanabi-live#2755]
cf #1057, #2257

I'm finally realizing that there are really _two_ pages that show the history of the seed.

One is the typescript client one that you get from the lobby, that looks something like this:
![image](https://user-images.githubusercontent.com/3750940/208521883-c9c46836-fef8-4811-ac58-39a102aaaf8b.png)

Thte other is the one generated by the Go server that is accessible even without login, that looks like this:
![image](https://user-images.githubusercontent.com/3750940/208522064-b913d959-e248-4cc5-850a-f3c4f2db8425.png)

It seems like it might be better if we consolidate these to just one page instead of two separate ones.

**Comment by vEnhance** [comment]
Also, contrary to the claim in #2257, as far as I can tell it is *not* the case that all the games are sent to the user in the Go version of the page. Instead, it looks like only a subset of the games are being sent based on the pager/AJAX.

This means for example that any statistics would have to be calculated server side. It also makes it impossible to e.g. sort by score right now. Would need to modify the API endpoint.

**Comment by Zamiell** [comment]
what is the motivation behind consolidating them?
it seems like worse UX to leave the client to view history.
for example, a common pattern is to view history, and then click on the create shared replay button on the last game.
if that was completely external, then doing that sequence would send you out of the client and then back into the client, which is terrible.

**Comment by vEnhance** [comment]
Oh I see. That makes sense, I hadn't thought about the leaving-client part.
It had just seemed odd to me to have two different pages with the same functionality.

I suppose it's fine to just maintain both (it just means e.g. some of the issues I linked above have to essentially be done twice).
