### ISSUE TITLE
You can get stuck "playing a game" even if it's in Shared-review

### ISSUE THREAD

**Issue by Krycke** [Hanabi-Live/hanabi-live#2758]
Sometimes you can get stuck after a game has finished and entered shared-review. You can't create a new game until the everyone in the shared replay has left and the game has been removed. Until then the server claims that "you are already playing a game".

Suggestion for a fix. When the server want to alert you that "you are already playing a game", check to see if that game is actually running, if not, remove the map entry, and release the player.

**Comment by Zamiell** [comment]
sure
