### ISSUE TITLE
Feature request: Add a "?" note/symbol, similar to kt and fix

### ISSUE THREAD

**Issue by pianoblook** [Hanabi-Live/hanabi-live#2774]
I very often have some unresolved questions/uncertainties about certain cards, or want to remember myself that others might have such uncertainties. 

[fix] notes are *okay* for this purpose, but personally I'd love to be able to differentiate between _"Fixes"_ (which are a reminder for some sort of specific _action_, like OOOs, tempo clues, Trash clues, etc) and, like..."Questions".

To help illustrate the point, here are a few scenarios where I would love to use this feature:

- Wondering if someone is called to blind-play or not, such as a Pull, Clandestine Finesse, etc. I'd slap a [f] [?] note on it.
- Wanting to pay attention to a card that might play if certain other cards are seen/touched. e.g., "Next round Bob could play his red card unprompted if I hold r5. [?]"
- Looking out for ENs/positionals/etc in endgame, or Stalling situations, etc. ("Did I draw a 5[?]")
- Wondering whether or not something *will* need a fix, e.g.: "this might have been CM'd, let's see. [fix] [?]

**Comment by Krycke** [comment]
I know Romain suggested an other colored border, would that be better then a big questionmark? And what would happen with [fix][?]

**Comment by Romain672** [comment]
https://github.com/Hanabi-Live/hanabi-live/issues/2317

**Comment by pianoblook** [comment]
No, I meant what I wrote - a nice big question mark symbol, just like [kt] and [fix] give their own symbols

**Comment by Krycke** [comment]
So in your last example what would be shown:
"this might have been CM'd, let's see. [fix] [?]"

Both a question mark and a wrench?

**Comment by pianoblook** [comment]
> Both a question mark and a wrench?

Don't see why not. Works for [kt] [fix] as well. 

I guess overlaying all three could start looking a bit silly, dunno.
