### ISSUE TITLE
Shared replays should keep their names

### ISSUE THREAD

**Issue by Krycke** [Hanabi-Live/hanabi-live#2781]
Why are we changing the name of the replay to "Shared replay of Game #12345". Is it not nicer to keep the name, as is?

**Comment by Zamiell** [comment]
i think its a remnant of before there were different colors in the lobby for the different "kinds" of tables.

an argument for keeping it is that it helps better distinguish between active games and shared replays.

if you dont think that is necessary, then feel free to submit a PR to remove it

**Comment by argothiel** [comment]
I also miss the games titles during the review, especially custom ones like "level 5" or "ref sieve".
