### ISSUE TITLE
critical indicator shows on blank cards

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#2796]
![image](https://user-images.githubusercontent.com/5511220/212998937-9db0f45f-2ba0-4226-9b56-821c3a4cf6cb.png)

**Comment by Zamiell** [comment]
happened on game 910480 turn 30

**Comment by Krycke** [comment]
Was this in-game or during review? I can't recreate this, can you give me a procedure to recreate?

**Comment by Zamiell** [comment]
hm we were in a hypothetical, give me a few to play around

**Comment by Zamiell** [comment]
i can't remember what i did to make it happen

**Comment by Krycke** [comment]
Tried a little more, but couldn't replicate this.

**Comment by Zamiell** [comment]
ah well i guess i will close for now
