### ISSUE TITLE
css is messed up on create game tooltip

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#2798]
![image](https://user-images.githubusercontent.com/5511220/213204462-69bb1926-0253-4bd2-8330-4eda4acdf1f8.png)

the magnifying glass row of icons is misaligned, needs to be fixed somewhere in the CSS or HTML i guess

**Comment by Zamiell** [comment]
also i think there should be a bit more space between the end of the input element and the magnifying glass, probably

**Comment by Zamiell** [comment]
after the latest PR it looks like this now for me:

![image](https://user-images.githubusercontent.com/5511220/213498352-7b40cd62-3977-4853-8b21-bef2b25c7bfe.png)

**Comment by Zamiell** [comment]
specifically, it doesn't look exactly centered, it looks more like its going towards the bottom.

this is on a normal 1080p monitor

**Comment by Krycke** [comment]
This looks like it did before. Have you refreshed completely to get the new css?

**Comment by Zamiell** [comment]
yep

**Comment by Zamiell** [comment]
i put some comments in #2800 that should probably be in this thread

**Comment by Zamiell** [comment]
another thing is that 
![image](https://user-images.githubusercontent.com/5511220/213524793-0c257873-9dff-4151-9268-d1642ea394e6.png)

here, the arrow looks greyed out, which isn't correct.
by having it be greyed out, it looks "disabled", which is communicating the wrong thing to the end-user.
i think it should be solid black probably?

**Comment by Zamiell** [comment]
and separately, im not sure what the triangle is supposed to be doing or what the original intent of the code was there

**Comment by Krycke** [comment]
Yeah, i didn't like the triangle either, but couldn't find it anywhere in the code. I suppose it's a triangle for a drop down list, but you are right, we don't really need it. Rather find a way to remove it completely and make the greyed out triangle solid as you say.
