### ISSUE TITLE
tooltip text in lobby might be too big

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#2800]
![image](https://user-images.githubusercontent.com/5511220/213497358-15b7a394-10ff-461b-93c6-1f561b2b2dd4.png)

it looks too big and weird i think

**Comment by Zamiell** [comment]
i think the reason it is so big is because the function is being reused from the game part, where all of the text is bigger, thus the bigger text isn't out of place there

**Comment by Krycke** [comment]
It's still giving me the old css, not the one with changes. I'm I, or you supposed to run build_critical?

**Comment by Zamiell** [comment]
oh you right actually

**Comment by Zamiell** [comment]
ok i rebuilt the client and now its updated

**Comment by Zamiell** [comment]
it does look centered now but

![image](https://user-images.githubusercontent.com/5511220/213524537-aa0bc0dd-5a61-4c7a-b5dd-8bafcca49352.png)

the little triangle looks off center

what is even the little triangle supposed to be.
i dont think its even supposed to be there maybe

**Comment by Zamiell** [comment]
oh this should be in the other thread

**Comment by Zamiell** [comment]
on the latest updated version of the code, the tooltip text is really big, so i think this is still an issue
