### ISSUE TITLE
Broken database entries for some games

### ISSUE THREAD

**Issue by kesslermaximilian** [Hanabi-Live/hanabi-live#2831]
While downloading games via the export api, I noticed that there are some games without a list of players being returned in the exported json.

Specifically, for 'No Variant', these games are
- https://hanab.live/export/357913
- https://hanab.live/export/357915
- https://hanab.live/export/358627
- https://hanab.live/export/358630
- https://hanab.live/export/358632
All of these show an empty list of players as well as actions (the latter not being a problem).
I also think that there is at least some occurrences also for other variants, but I have not investigated that so far.

This leads to unexpected behaviour at different parts of the website:
- When trying to watch a replay of these games (try e.g. https://hanab.live/replay/357913), you will receive an error message stating that the game could not be constructed (which makes sense, since in particular the number of players is unknown)
- When listing played games via the api, pages that would contain the above games return less items than expected, concretely
    - https://hanab.live/api/v1/variants/0?col[0]=0&page=1633&size=100 returns only 98 rows of data, the first two games listed above would be contained in that range
    - https://hanab.live/api/v1/variants/0?col[0]=0&page=1635&size=100 returns only 97 rows of data, the last three games listed above would be contained in that range

As of my knowledge, this is not big of an issue, these just seem to be some broken entries in the database and I don't see a particular need to do something about it, although it would of course be nice to resolve the issue by fixing/deleting the entries.

Also it would of course be interesting to know what caused these invalid entries to be in the DB in the first place, but I have no idea regarding this.

**Comment by Aigul9** [comment]
@kesslermaximilian There are plenty of games missing (around 6k at the moment). i think one of the main reasons is that unnecessary/similar variants were deleted and replaced by the new ones, therefore there was no need to keep junk games in the db.

**Comment by kesslermaximilian** [comment]
I know that there are a lot of 'missing' games in the sense that not all gameIDs ≤ (current max) are ids of actual games, but I do not consider that a problem.
If you query these, you will get an error stating 'Game #<id> does not exist in the database', which I think is perfectly fine and self-explanatory.

The games I mentioned above, however, fail this usual pattern, since there are actual entries in the DB for them, but the data for them is incomplete (missing player names), which leads to this ' Failed to initialize the game. Please contact an administrator.' error, which is a very different kind of error.

So I think that either, player names for these games should be re-added (if possible) or the games should be deleted entirely to ensure consistency of the stored data.

**Comment by kesslermaximilian** [comment]
Possible explanation: In the database schema, entries of `game_participants` are configured with `ON DELETE CASCADE` if a user gets removed from the database.

The `loadDatabaseOptionsToTable` function has a sanity check at `command_replay_create.go:395` to see if it finds as many participants in the table as there should be. In case it does not, the error returned to the user matches the error received when trying to watch replays for the games above.

Conversely, the http export function in `http_expor.go:47` does not have this check and just retrieves the players from the DB. If i read it correctly, though, it should still return all player names found, even if these are less that the number of the actual game. Implying that if the bug is in fact some players missing in the DB and the corresponding `game_participant` entries having been deleted, then it would be surprising that in fact in all of the cases above, all participants have been deleted.

I guess one should check the logs to get detailed information on what went wrong during game intialization.

**Comment by Zamiell** [comment]
> {"level":"error","ts":"May  21 15:36:38","caller":"src/command_replay_create.go:396","msg":"There are not enough game participants for game #357913 in the database. (There were 0 player rows and there should be 2.)","stacktrace":"main.loadDatabaseOptionsToTable\n\t/root/hanabi-live/server/src/command_replay_create.go:396\nmain.replayCreate\n\t/root/hanabi-live/server/src/command_replay_create.go:117\nmain.commandReplayCreate\n\t/root/hanabi-live/server/src/command_replay_create.go:58\nmain.websocketMessage\n\t/root/hanabi-live/server/src/websocket_message.go:110\ngithub.com/gabstv/melody.(*Session).readPump\n\t/root/go/pkg/mod/github.com/gabstv/melody@v1.0.2/session.go:133\ngithub.com/gabstv/melody.(*Melody).HandleRequestWithKeys\n\t/root/go/pkg/mod/github.com/gabstv/melody@v1.0.2/melody.go:192\nmain.httpWS\n\t/root/hanabi-live/server/src/http_ws.go:114\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168\ngithub.com/gin-contrib/sessions.Sessions.func1\n\t/root/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.4/sessions.go:54\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168\ngithub.com/gin-gonic/gin.CustomRecoveryWithWriter.func1\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168\ngithub.com/gin-gonic/gin.LoggerWithConfig.func1\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/logger.go:241\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/go-1.13/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/lib/go-1.13/src/net/http/server.go:1890"}

> {"level":"info","ts":"May  21 15:36:38","caller":"src/session.go:123","msg":"Error - Failed to initialize the game. Please contact an administrator. - James"}

**Comment by Zamiell** [comment]
i deleted these 5 games from the database now.
@kesslermaximilian do you want to do a PR that adds the same sanity check to http_export?

**Comment by kesslermaximilian** [comment]
I wanted to follow up on this, since the above mentioned games are apparently not the only ones affected. If you look at https://hanab.live/api/v1/variants/0?col[0]=0&page=822&size=100, then you can see that game 181416 is listed with ```{"id":181416,"num_players":3,"score":25,"users":"frollo9386, robense","datetime":"2020-05-25 - 18:02:03 UTC","seed":"p3v0s129"}```
, so there is a player missing in the list. Indeed, when you try to export the game, then you get an 'Internal Server Error' (which is the expected behaviour since #2832).
As a sidenote, this is also the first game I have seen where only some of the users are missing.

For consistency reasons, I think it would be nice to come up with a general solution on how to handle these situations, after all, this is still some inconsistency. There are two questions to answer:

- What is to be done with all games currently in the DB that are affected by this?
- What can be done to prevent these situations in the future?

For the first, an easy solution would be of course to delete the games, like it has been done for the initial 5 games. If this does not affect too many games, this is probably okay. Then, the answer to the second question would probably be to delete such games automatically upon user deletion (Deleting them from the DB should be easy, but I'm not sure how hard it is to also automatically update statistics on deletion). Of course, this hugely depends on how often / why users are deleted from the database, I suppose this is a manual process by the admins.

Another approach I would personally like to see is to just keep the games around and be okay with the concept of games not having associated players anymore. To show replays, exports etc, we could then just insert dummy names. I don't know if this causes any problems with other website behaviour, but I think this could also be a clean solution. In that case, point 2 will be trivial.

Let me know what you think about this. In case this is relevant for the discussion: I could write some code that finds all the affected games, in particular their total number.

**Comment by Zamiell** [comment]
> What is to be done with all games currently in the DB that are affected by this?

deleting them is fine

> What can be done to prevent these situations in the future?

if you look at this file:
<https://github.com/Hanabi-Live/hanabi-live/blob/main/install/database_schema.sql>
you can see that in some cases, there is a "ON DELETE CASCADE".
for example, if a user is deleted, then the corresponding game_participant entry is deleted.

however, when this occurs, the corresponding "game" table entry is not automatically cleaned up, so I hypothesize that the remaining corrupted games are cases where a user was deleted but the corresponding games were not deleted. 

> Another approach I would personally like to see is to just keep the games around and be okay with the concept of games not having associated players anymore.

not a fan personally

>  could write some code that finds all the affected games, in particular their total number.

sure

**Comment by Zamiell** [comment]
> What can be done to prevent these situations in the future?

i can't even remember the last time i deleted a user, its not something that regularly happens, i think i've only ever deleted test accounts

**Comment by kesslermaximilian** [comment]
Ok, got a list of the games with invalid number of players that I could identify:

[invalid_game_ids.txt](https://github.com/Hanabi-Live/hanabi-live/files/11977284/invalid_game_ids.txt)

Format for each row is `(game_id, variant_id, num_players, players...)`, where `num_players` is the expected number of players reported by the site and `players...` is the list of player names actually found in the database.

**Comment by kesslermaximilian** [comment]
Also something that came to my mind: One could add an `ON DELETE` trigger to the games_participants table that deletes the corresponding games each time an entry in that table is deleted. Then a DB deletion of a user cascades to the `games_participants` table and ultimately to the `games` table as well, preventing these kind of inconsistencies in the future.

I'm not exactly sure how to do it (not very much familiar with PostgreSQL), but I think it should be possible.

Is that something you could imagine adding, or is it just not needed because you simply don't delete users?

Another option would be to just write some dedicated database function that deletes a user and cleans stuff up and remember to use it instead of directly deleting users.

**Comment by kesslermaximilian** [comment]
Sure, I'll send a PR if I get it to work. I suppose you'll delete the games listed above?

**Comment by Zamiell** [comment]
yeah im doing it now

**Comment by Zamiell** [comment]
all the games from the [invalid_game_ids.txt](https://github.com/Hanabi-Live/hanabi-live/files/11977284/invalid_game_ids.txt) are deleted now, thank you very much

**Comment by Zamiell** [comment]
should we close this now?

**Comment by kesslermaximilian** [comment]
Yes, I don't see anything left to do (unless I missed some games, then we can still delete them later). At least with the PR merged, there shouldn't be any more.

Thanks as well for the work.
