### ISSUE TITLE
Support Ctrl + click on cards to open note menu

### ISSUE THREAD

**Issue by kesslermaximilian** [Hanabi-Live/hanabi-live#2837]
I'm not a mac user, but this issue just came up in the discord and it seems reasonable:

On mac, right click is sometimes not available (apparently the default pad does not support it or sth), mac usually uses Ctrl + click for stuff that is right click somewhere else (open menus on desktop etc)

We should support that as well in the web interface to open the note menu.
As far as I know, Ctrl + click currently has no defined binding, so we should just add that.

In case you think this is fine, I'd probably also be able to send a PR for that

**Comment by Zamiell** [comment]
ctrl + left click is already taken by arrow, so you can't overload that functionality to note as well

**Comment by Zamiell** [comment]
> apparently the default pad does not support it or sth

this is nonsense, i've used a macbook pro & macbook air for over 10 years now and right clicking has never been a problem

**Comment by kesslermaximilian** [comment]
> ctrl + left click is already taken by arrow, so you can't overload that functionality to note as well

Is it? At least for me, nothing happens when I do so in game. Also thought the arrow shortcut was Ctrl + right-click, not left-click.

Anyway, I can't judge on this being needed or net, I was just told that this is the case and decided to implement it.

I'll close this, if this comes up again we'll try to figure out what's going on on that mac device.

**Comment by Zamiell** [comment]
> thought the arrow shortcut was Ctrl + right-click, not left-click

oh you are right, i think this changed at some point
