### ISSUE TITLE
Variants API returning less entries than requested on some pages

### ISSUE THREAD

**Issue by kesslermaximilian** [Hanabi-Live/hanabi-live#2840]
Consider `https://hanab.live/api/v1/variants/1?col[0]=0&page=197&size=100`. This is supposed to give information on games played in variant `1` (6 Suits) in chunks of size 100, where you can iterate over the chunks by setting the page.
However, the API sometimes returns responses (as above) that only contain 99 entries, not 100.
I refreshed the page and tried several network, does not seem to be a cache issue and also seems to be persistent.

Other examples on requests that give only 99 rows are:
- https://hanab.live/api/v1/variants/3?col[0]=0&page=246&size=100
- https://hanab.live/api/v1/variants/11?col[0]=0&page=102&size=100

As a remark, note that these are not the last page of their variant (in which case we expect less than 100 games potentially), just increase the page number and you will see that you'll get 100 entries again.
This seems to be very rare (these are the only 3 occurrences I found among all pages for the first 200 variants).

Currently, I have no idea on why this would happen (also, it's curious that it's always 99 entries returned in case some are missing), but since this seems to occur consistently at exactly these pages, it seems that there is something wrong either with the DB query or with some data in the DB relating to these queries, both of which we should fix.

**Comment by kesslermaximilian** [comment]
Update: Found a fourth occurrence, this time with only 98 entries, so 99 is not consistent after all:
https://hanab.live/api/v1/variants/783?col[0]=0&page=0&size=100

**Comment by Zamiell** [comment]
you can see the source code in: `api_variants.go`
i didn't build this code, takis did, so there might be some bug where 100 results are getting returned by then some are being filtered out afterward, maybe you want to do some investigating?

**Comment by kesslermaximilian** [comment]
Got an idea now, related to #2831: The list I sent you there only included games that were listed by the variants API (since that's how I queried them). Looking at the code, I think that the API would fail to return games that have no participants at all in the DB.

Can you check game 357914? Exporting it yields to the 'Internal Server Error' message. I would suppose that this is a `Rainbow (6 Suits) game` that has no associated `game_participants` and therefore raises this error and also does not show up in the API list above.

**Comment by Zamiell** [comment]
> Can you check game 357914? Exporting it yields to the 'Internal Server Error' message. I would suppose that this is a Rainbow (6 Suits) game that has no associated game_participants and therefore raises this error and also does not show up in the API list above.

that is correct, there is one entry for that ID, but no game_participant rows

**Comment by Zamiell** [comment]
i'll go ahead and delete all such games.

what is the corresponding sql query to find such games?

something like this?

```sql
select id from games where not exists ( select id from game_participants where game_participants.game_id = id );
```

I tried that and it returned 0 results

**Comment by kesslermaximilian** [comment]
These games should probably be in there, all returning the server error as well:

357914
358614
358628
358629
358631

**Comment by Zamiell** [comment]
```
hanabi=> select games.id, games.num_players, count(game_participants.game_id) as found_players from games left outer join game_participants on games.id = game_participants.game_id group by games.id having count(game_participants.game_id) != games.num_players;
   id   | num_players | found_players
--------+-------------+---------------
 357914 |           2 |             0
 358614 |           5 |             0
 358628 |           3 |             0
 358629 |           5 |             0
 358631 |           3 |             0
 646396 |           2 |             0
(6 rows)
```

**Comment by Zamiell** [comment]
ok, all these games are deleted now.

did that also fix the "99" issue that you describe in the OP?

**Comment by kesslermaximilian** [comment]
Yes, thanks once again. Seems like #2831 was indeed the cause and the API code is correct.
