### ISSUE TITLE
Sudoku UI

### ISSUE THREAD

**Issue by kesslermaximilian** [Hanabi-Live/hanabi-live#2852]
There have been some discussions about this already, and I haven't found a clean solution yet, so I'll just start an issue to let people discuss how the Sudoku UI should be.
I think we can agree that the UI should
- Make the stack starts clear. This is needed to figure out where the other stacks can be started at.
- Make it clear how many cards have been played already per stack. This is useful for priority and also just to track (endgame)-progress.
- Make it clear which 'set' of cards is played already. This is useful to reduce possibilities of clued cards in the own hand by good touch.

The current UI achieves the first two, but I hadn't thought of the third one, though admittedly, it'd really be something nice to have.
Suggestions to improve this that I heard so far were

- Say a suit starts with 2, then we can display 23451 in that order. We can then separate the played cards from the rest by an underscore, so if 23 are played, we can show 23_451
- Same, but the played cards are in boldface. Disclaimer: I currently don't know how to do this, since the Konva text-element does not support different styles within the same text element. Happy with help here.
- Remove 'x cards played' and replace it with a list of the played cards, e.g. '23 played'. Maybe with commas?

Further suggestions very welcome

**Comment by Zamiell** [comment]
> Remove 'x cards played' and replace it with a list of the played cards, e.g. '23 played'. Maybe with commas?

could be `2, 3 played, 4, 5, 1 remaining`

**Comment by Zamiell** [comment]
or `23 played, 451 remaining` is shorter

**Comment by Zamiell** [comment]
and change the stack to `Finished` once it is completed please like how it works in up or down

**Comment by kesslermaximilian** [comment]
> and change the stack to `Finished` once it is completed please like how it works in up or down

That's happening already, in Keldon it's just in the hover (yeah not great I agree).

**Comment by Zamiell** [comment]
having it be in the hover is effectively useless

**Comment by kesslermaximilian** [comment]
Yes, I can see that by now, I'm working on your one-line suggestion rn

**Comment by kesslermaximilian** [comment]
![sudoku_ui](https://github.com/Hanabi-Live/hanabi-live/assets/82446011/49422c99-2ea5-4cf0-a952-b0e1ba3a112d)

Looks a bit crammed still (Imagine the first line gone for now).

**Comment by Zamiell** [comment]
1. use `remain` instead of `missing` as it is slightly smaller horizontally
2. in this scheme, the "Starts at 4" line is completely superfluous, because the "4 played, 5123 remain" line communicates that already, so just use that and then remove all of the code relating to the second line

**Comment by kesslermaximilian** [comment]
> Imagine the first line gone for now)

**Comment by Zamiell** [comment]
3. for unstarted stacks, instead of showing nothing, show `can start with 12345` / `can start with 345` / etc.

**Comment by kesslermaximilian** [comment]
maybe even `not` instead of `remain`. A little bit more ugly regarding language, but saves another few characters and increases font size?

**Comment by Zamiell** [comment]
Sure, up to you, depending on how squished it gets

**Comment by kesslermaximilian** [comment]
![sudoku_ui_updated](https://github.com/Hanabi-Live/hanabi-live/assets/82446011/fa604bf4-169a-476f-bad1-77ffc0ca0a3f)

I have this suggestion now (dukes idea), even more compact since we avoid all text. I like that numbers don't move their, everything is very static except that new ones appear when you play cards.

**Comment by kesslermaximilian** [comment]
I hope this is satisfying for everyone now!
But still open for improvement suggestions, as long as you can keep stuff compactly in one line.
