### ISSUE TITLE
sudoku ui

### ISSUE THREAD

**Issue by Zamiell** [Hanabi-Live/hanabi-live#2859]
![image](https://github.com/Hanabi-Live/hanabi-live/assets/5511220/be39d514-1008-47e8-af8e-8156a326ff82)

start text overlaps

suggestion: change `Start: [12345]` to `Start: [Any]`

**Comment by Zamiell** [comment]
even after this suggestion, text is too cramped:

![image](https://github.com/Hanabi-Live/hanabi-live/assets/5511220/407dc9ee-356e-4743-bc98-db03f0e775c6)

**Comment by Zamiell** [comment]
Also the labels don't look centered.
For example, look at the label under the green 5, the left bracket is to the left of the card, but the right bracket is aligned with the right of the card.

**Comment by Zamiell** [comment]
![image](https://github.com/Hanabi-Live/hanabi-live/assets/5511220/235d61f5-d003-449f-82eb-0d6a9afde10f)

says 0 when a 1 is played under purple stacks ??

**Comment by kesslermaximilian** [comment]
> ![image](https://user-images.githubusercontent.com/5511220/256542154-be39d514-1008-47e8-af8e-8156a326ff82.png)
> 
> start text overlaps
> 
> suggestion: change `Start: [12345]` to `Start: [Any]`

seems good, you already did that

**Comment by kesslermaximilian** [comment]
> even after this suggestion, text might be too cramped:
> 
> ![image](https://user-images.githubusercontent.com/5511220/256544022-407dc9ee-356e-4743-bc98-db03f0e775c6.png)

For me it's way less cramped, probably depends on size of display? I can test some different solutions.

**Comment by Zamiell** [comment]
> probably depends on size of display?

im on a super-normal monitor in 1920x1080 resolution

**Comment by kesslermaximilian** [comment]
> ![image](https://user-images.githubusercontent.com/5511220/256544903-235d61f5-d003-449f-82eb-0d6a9afde10f.png)
> 
> says 0 when a 1 is played under purple stacks ??

I have no idea how this can happen. If you look at the implementation, the number computed is computed as (rankOffset + stackStart -1)%5 +1, so this being 0 would mean rankOffset+stackStart = 0, but offSet is nonnegative since its an array index and stackStart as well, since it's the rank of some card.

Also never saw this before.

**Comment by kesslermaximilian** [comment]
> Also the labels don't look centered. For example, look at the label under the green 5, the left bracket is to the left of the card, but the right bracket is aligned with the right of the card.

I don't know, could this just be a general problem with the UI elements, that they are not perfectly positioned?

**Comment by Zamiell** [comment]
> I don't know, could this just be a general problem with the UI elements, that they are not perfectly positioned?

not sure, potentially. it could be that you need to adjust the XY of where they start at, or maybe there is a "centered" option

**Comment by Zamiell** [comment]
> I have no idea how this can happen. If you look at the implementation, the number computed is computed as (rankOffset + stackStart -1)%5 +1, so this being 0 would mean rankOffset+stackStart = 0, but offSet is nonnegative since its an array index and stackStart as well, since it's the rank of some card.

i replayed the seed and the bug didn't happen again, so for now ignore this

**Comment by kesslermaximilian** [comment]
> > I don't know, could this just be a general problem with the UI elements, that they are not perfectly positioned?
> 
> not sure, potentially. it could be that you need to adjust the XY of where they start at, or maybe there is a "centered" option

I think they are already centered.

**Comment by Zamiell** [comment]
> Are your pictures with windows?

yes, i am on windows 10, which is what most users of the website use.

maybe a good PR would be to include a specific font which would unify the look of the game UI across different OS.

**Comment by Zamiell** [comment]
> I think they are already centered.

then double check for any leading or trailing whitespace included before or after the square brackets.
otherwise we can try adjusting the XY start positions of the labels

**Comment by kesslermaximilian** [comment]
Really not sure about that. I have no idea of other OS'es than linux (and also nothing of fonts) and I don't plan to change so tbh.

**Comment by kesslermaximilian** [comment]
> > I think they are already centered.
> 
> then double check for any leading or trailing whitespace included before or after the square brackets. otherwise we can try adjusting the XY start positions of the labels

Already did, there is none.

**Comment by kesslermaximilian** [comment]
Yeah it's just not centered perfectly. Also in other variants like Up or Down, if you look closely, it's not in the center. It's just not been noticed before since the text was so short. I'll adapt the positions.

**Comment by kesslermaximilian** [comment]
> ![image](https://user-images.githubusercontent.com/5511220/256544903-235d61f5-d003-449f-82eb-0d6a9afde10f.png)
> 
> says 0 when a 1 is played under purple stacks ??

Apparently this was actually a bug occuring a bit randomly. Fixed it now (hopefully).

**Comment by kesslermaximilian** [comment]
I don't think I can fix the stack-centering issue, at least for now I don't see what's wrong with these, the code looks fine.
