### ISSUE TITLE
Sudoku with 4 Suits

### ISSUE THREAD

**Issue by kesslermaximilian** [Hanabi-Live/hanabi-live#2861]
I thought about it (and talked a bit with Hoddie), and I think we can make sense of 4-suit variants of Sudoku. The idea would be that we only have ranks 1,...,4 for each suit and then wrap around from 4 to 1.
The deck gets pretty small then (only 4 * 4 * 2 = 32 cards), so the pace/efficiency values would be:

- 3p: pace 4, efficiency 1.06
- 4p: pace 4, efficiency 1.14
- 5p: pace 1, efficiency 1.45
- 6p: pace 4, efficiency 1.14

(All assuming no dark suits, dark suits are just not winnable)

While 5p is certainly challenging, I think it's an interesting idea similar to 3-suit variants.

Would you accept a PR for these?

**Comment by Zamiell** [comment]
ok
