### ISSUE TITLE
Sudoku + Follower Inaccurate Strike

### ISSUE THREAD

**Issue by rmhulett** [Hanabi-Live/hanabi-live#2863]
Turn 30 of this game: https://hanab.live/game/2500#30
- Two 5 cards have already been played, and y4 is on the board
- reyna (Follower) plays y5
- marked as a strike/misplay, but should be a valid play

reyna was able to play other cards successfully (y4 on turn 18, y1 on turn 42) so maybe it's something specific about the Follower logic for 5s?

**Comment by rmhulett** [comment]
Oops, here's the replay link: https://hanab.live/shared-replay/1002131#30

**Comment by rmhulett** [comment]
Oh, Follower is implemented by looking at the top card in each stack and assuming exactly the cards less than or equal to that value have been played: https://github.com/Hanabi-Live/hanabi-live/blob/main/server/src/characters.go#L458

**Comment by kesslermaximilian** [comment]
I see, I did not think of detrimental characters when implementing Sudoku. Also one thought on that

- Do we want follower to have the described behaviour, i.e. actually depend on the ranks of cards?
- Or would we want it to refer to the 'amount of cards played' in each stack, i.e. 'Cannot play n-th card of stack unless 2 other stacks contain at least n cards'.

In either case, I can provide a fix for that.

**Comment by Zamiell** [comment]
whatever you think is better

**Comment by kesslermaximilian** [comment]
Then I'll go with the first approach. Simpler to understand and extra Sudoku mechanic.

**Comment by kesslermaximilian** [comment]
Am I correct in the assumption that there is actually no client implementation of the Follower character? If you open a regular game and start a hypothetical, you can just play your cards as if the character had no restriction at all...?
If so, maybe we should add a general issue that the client has no detrimental character implementation.

I fixed the server side now with Sudoku at least, in case there is a place in the client that needs fixing (didn't find one), let me know.

**Comment by Zamiell** [comment]
> Am I correct in the assumption that there is actually no client implementation of the Follower character?

no idea

**Comment by kesslermaximilian** [comment]
> > Am I correct in the assumption that there is actually no client implementation of the Follower character?
> 
> no idea

I made a hypo in a NoVar game and I could play cards as follower without restriction. So at least to me, it seems like it's missing.
