### ISSUE TITLE
cm'd cards are not taken into account when determining global trash during the game

### ISSUE THREAD

**Issue by Aigul9** [Hanabi-Live/hanabi-live#2868]
ex: 2 y4s have different level of brigthness, although both of them are trash (see below)
![image](https://github.com/Hanabi-Live/hanabi-live/assets/46625461/7ab264cd-fdac-49cb-aa37-db64da595b5e)

it's not happening in the replay
https://hanab.live/replay/1005674

was it always the case?

**Comment by Zamiell** [comment]
its intended because cm indicates that the card is important
