### ISSUE TITLE
Teal suit in dual color (5 suits) should use the actual teal suit instead of green

### ISSUE THREAD

**Issue by unsoftcapped3** [Hanabi-Live/hanabi-live#2869]
![image](https://github.com/Hanabi-Live/hanabi-live/assets/75136164/e9fba08c-09a4-4219-976d-fc30927e20ee)
these "teal" cards look exactly like the green cards in no var games while there is an actual teal suit in 6 suits and it's not being used for dual color 5 suits even though they're the same color

**Comment by unsoftcapped3** [comment]
https://discord.com/channels/140016142600241152/140016142600241152/1139446611374772324 for reference

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by unsoftcapped3** [comment]
where's the file that controls this?

**Comment by Zamiell** [comment]
should be fixed now
