### ISSUE TITLE
Links to the doc have to be in UPPERCASE

### ISSUE THREAD

**Issue by Metylene** [Hanabi-Live/hanabi-live#2872]
When not logged, you can see "Do **NOT** reuse any of your [previous passwords](https://github.com/Hanabi-Live/hanabi-live/blob/main/docs/passwords.md)!" but the link send to 404 github page. The correct link is [PASSWORDS.md](https://github.com/Hanabi-Live/hanabi-live/blob/main/docs/PASSWORDS.md). This is also a problem when you want to read [VARIANTS.md](https://github.com/Hanabi-Live/hanabi-live/blob/main/docs/VARIANTS.md) before creating a new game.

That's because all files in the [docs](https://github.com/Hanabi-Live/hanabi-live/tree/main/docs) are in uppercase. This is also a problem when you want to read [VARIANTS.md](https://github.com/Hanabi-Live/hanabi-live/blob/main/docs/VARIANTS.md) before creating a new game.

I tested it with 3 browsers, on Windows.

**Comment by vEnhance** [comment]
looks like james fixed this in 02ea7f3 (re-open if i'm mistaken)

**Comment by Zamiell** [comment]
yup, thanks for the report @Metylene
