### ISSUE TITLE
Bugs found in Special-Ones and Special-Fives Variants

### ISSUE THREAD

**Issue by HelanaAsh** [Hanabi-Live/hanabi-live#2873]
Noticed special-ones and fives don't behave appropriately. Please note, hypotheticals are perfectly fine.

1. We were playing pink-ones and black. On turn 14, you notice b1 does not get clued along with b4, which should be the case since 
    b1 is a pink 1 and should respond to all ranks. On the same replay, earlier in the game you will notice that pink-ones respond to 
    color clues, therefore behaving more like brown-ones than pink-ones.
    https://hanab.live/replay/1009978#14
2. We tried replaying the same var and you notice on turn 2, g1 does not get clued along with r3.
    https://hanab.live/replay/1009979#2
3. To understand if this bug is extended to both pink-ones and pink-ones or is exclusive to pink-ones, we tried playing fink-fives and 
    white next. You notice on turn 2, r5 and b5 do not respond to the 2 clue. So pink-ones/fives are behaving sort of like brown- 
    ones/fives.
    https://hanab.live/replay/1009982#2
4. We tried to play null-ones next to check if the bugs are specific to pink-ones or applies to other special-ones. On turn 6, b1 
    responds to blue clue. So null-ones sort of also behave like brown-ones, although we did not test b1 with a rank in this particular 
    game.
    https://hanab.live/replay/1009984#6
5.  Muddy-rainbow-ones also appeared to be buggy. On turn 4, y1 is not touched with a purple clue.
     https://hanab.live/replay/1009985#4

**Comment by Zamiell** [comment]
i suspect this is due to my recent refactoring, i will take a look

**Comment by Zamiell** [comment]
i wasn't able to reproduce the bug on my local development version of the site, which means that the bug was already fixed somewhere along the line.

i updated the main website to the latest version, so the bug should be gone now.
