### ISSUE TITLE
Hypo with "One Extra Card" mode on

### ISSUE THREAD

**Issue by Kowalski1337** [Hanabi-Live/hanabi-live#2874]
**Describe the bug**
Editing cards in hypo works wrong if "One Extra Card" settings turned on. Editing cards causes multiple cards replacement.

**To Reproduce**

1. Create game with "One Extra Card"
2. Terminate the game
3. Enter hypothetical
4. Edit any card
5. Several cards will be edited

**Expected behavior**
Only chosen card will be edited

**Comment by Zamiell** [comment]
has this always been the case or is it a new bug?

**Comment by Zamiell** [comment]
i tried the steps you listed and i was not able to reproduce the bug, please provide more specific steps to reproduce
