### ISSUE TITLE
Chat command to terminate games

### ISSUE THREAD

**Issue by SlackingSleeper** [Hanabi-Live/hanabi-live#2884]
If you are on mobile it is currently impossible to terminate a game. It can be very annoying and mobile users have to ask other players to terminate the game.

A chat command for terminating the game seems like the simplest solution to me.

**Comment by kesslermaximilian** [comment]
We could simply implement `/terminate` as a chat command to do this, seems easy to do.

**Comment by Zamiell** [comment]
> We could simply implement /terminate as a chat command to do this, seems easy to do.

seems fine
