### ISSUE TITLE
Game breaks and throws an error when trying to bottom-deck blind play during a hypothetical during a post-game replay

### ISSUE THREAD

**Issue by shemetz** [Hanabi-Live/hanabi-live#2886]
**Describe the bug**
I got this error:
> TypeError: Failed to find the card at order: 49
    at Ce (https://hanab.live/public/js/bundles/main.6054.min.js:1:46728)
    at eV (https://hanab.live/public/js/bundles/main.6054.min.js:168:50223)
    at https://hanab.live/public/js/bundles/main.6054.min.js:9:109473
    at lU.produce (https://hanab.live/public/js/bundles/main.6054.min.js:9:109618)
    at https://hanab.live/public/js/bundles/main.6054.min.js:9:109458
    at DT (https://hanab.live/public/js/bundles/main.6054.min.js:168:55969)
    at nV (https://hanab.live/public/js/bundles/main.6054.min.js:168:54392)
    at https://hanab.live/public/js/bundles/main.6054.min.js:9:109473
    at lU.produce (https://hanab.live/public/js/bundles/main.6054.min.js:9:109618)
    at https://hanab.live/public/js/bundles/main.6054.min.js:9:109458

and it showed up for all players and prevented us from continuing the game replay.

It happened to us just now, on game https://hanab.live/shared-replay/1042296#56

**To Reproduce**
Steps to reproduce the behavior (probably, I haven't tried it again):

1. enable "bottom-deck blind play"
2. play and complete a game.  possibly necessary to do a bottom-deck blind play during it, unsure.
3. enter replay mode (shared replay, unsure if necessary to reproduce)
4. enter hypothetical during one of the last turns 
5. during that hypothetical, do a bottom-deck blind-play
6. -> game throws up, cannot continue

**Expected behavior**
no error

**Screenshots**
![image](https://github.com/Hanabi-Live/hanabi-live/assets/6516621/3044e8ba-583d-4894-a987-3c038c948fd2)

**Comment by Zamiell** [comment]
should be fixed now
